### ISSUE TITLE
Low performance on the `Generate graphics` stage

### ISSUE THREAD

**Issue by AdriiiPRodri** [wazuh/wazuh-qa#2237] opened 2021-11-18 13:25 UTC
In the last launches of the workload pipeline, we have detected a low performance in the stage "Generate graphics". Here we can see an example:

![image](https://user-images.githubusercontent.com/15522808/142423376-6c4f1413-a752-4713-9ad1-5f3472aa9306.png)

We need to analyze the scripts/tools in charge of generating these graphs, detect the problem, and fix it.

**Comment by mcarmona99** [comment] 2022-04-08 15:01
## Issue update



The tasks to generate the graphics are created when using the `createDataVisualizerTask` of the Wazuh CICD repository.

The `data-visualizer` is the binary used, and as we can see in the pipeline console. This binary is generated by the `wazuh_testing.scripts.data_visualizations:main` function, which instantiates a `DataVisualizer` object and uses its `plot` method.

https://github.com/wazuh/wazuh-qa/blob/0e769da909874a1f5f791c8bf132e6ffba0e4c6e/deps/wazuh_testing/wazuh_testing/tools/performance/visualization.py

Time taken to generate graphics for `remoted` stats:

```
$ time data-visualizer -s ./data/wazuh-remoted_stats.csv -t remote -d . -n wazuh-remoted_stats

real	0m1,237s
user	0m2,192s
sys	0m2,858s
```


The time taken to generate graphics for `binaries` data is higher:

```
$ time data-visualizer -s ./data/binaries/wazuh-apid_child_1.csv -t binary -d . -n binaries

real	0m2,416s
user	0m3,890s
sys	0m4,669s
```

When we generate graphics for all the binaries, the time taken is even higher:

```
$ time data-visualizer -s wazuh-apid_child_1.csv wazuh-apid_child_2.csv wazuh-apid.csv wazuh-clusterd_child_1.csv wazuh-clusterd_child_2.csv wazuh-clusterd.csv -t binary -d . -n binaries

real	0m2,746s
user	0m4,532s
sys	0m4,924s
```

It does not seem to be a bottleneck here, as times taken are not as high as CI machines'.

The creation of all graphics is done with sentences like the one shown above. Therefore, the high times cannot be due to these sentences, as we have seen the times are not high enough.

I have used a Workload pipeline build example to see times and logs. 

30 MINUTES SPENT IN THE GENERATE GRAPHICS STAGE

```
11:10:11  [Pipeline] stage
11:10:11  [Pipeline] { (Generate graphics)
...
11:41:11  [Pipeline] // stage
11:41:11  [Pipeline] stage
11:41:11  [Pipeline] { (Install cluster tests requirements)
```

The high times may be caused by the healthcheck in the run method of the class representing the task. The healthcheck wait untill the task is running.

The sleep interval value is 5 and the retries value is 4. The healthcheck is, therefore, called with a sleep value of 5.
But in this case, the condition is not True so the values are not changed (still 5 and 4). 

The healthcheck function calls other functions that are the ones printing some specific logs in the console. These logs are useful to see when each task started and ended.

Logs:

```
run-task
describe-task
describe-task
describe-task
...
```
  
  
These `describe-tasks` logs are repeated until the task is running (healthcheck we commented above).
      


In this healthcheck is where we could say the high time is waited, we are waiting for 5 seconds * retries.

After the healthcheck, 10 seconds are waited.

Finally, a healthcheck lasting 30 seconds * retries is done waiting for the task to be stopped.

Summarizing, a generate graphics task spents

**Wait until task running => 5 * retries (max 60) seconds + 10 seconds (fixed)
Wait until task stopped => 30 * retries (max 60) seconds**

All of the tasks are run in parallel, so the time spent should be the time taken by the task spending the highest time.


In the real case, we can see that they don't appear to be run in parallel:

Generate graphics tasks started at 11:10:11 and ended at 11:41:11:
 
1st task finished (run successfully log) at 11:12:06
2nd task finished (run successfully log) at 11:14:34
3rd task finished (run successfully log) at 11:16:32
4th task finished (run successfully log) at 11:18:43
5th task finished (run successfully log) at 11:20:48
6th task finished (run successfully log) at 11:22:59
7th task finished (run successfullly log) at 11:25:34
8th task finished (run successfully log) at 11:27:39
9th task finished (run successfully log) at 11:29:56
10th task finished (run successfully log) at 11:32:01
11th task finished (run successfully log) at 11:34:00
...

11 tasks (10 workers + 1 master)


The rest of the tasks seem to be run in parallel, as some of their "run successfully" logs were printed at the same time.

Note: the total number of tasks is equal to (the number of workers + 1 (master)) * (number of monitored processes + number of monitored stats). In this example, 33 tasks.


Work in progress...

**Comment by mcarmona99** [comment] 2022-04-11 09:53
## Issue update

After investigating deeper about this issue, I have seen that the `data-provider` tasks are correctly run in parallel and they are not taking a lot of time. For instance, the following are the creation, starting, and stopping times of some of these tasks:

**Task 1:**

Created: `11/4/2022, 8:45:49 UTC`
Started: `11/4/2022, 8:46:47 UTC`
Stopped: `11/4/2022, 8:47:19 UTC`

**Task 2:**

Created: `11/4/2022, 8:45:34 UTC`
Started: `11/4/2022, 8:46:42 UTC`
Stopped: `11/4/2022, 8:47:21 UTC`

**Task 3:**

Created: `11/4/2022, 8:45:42 UTC`
Started: `11/4/2022, 8:46:52 UTC`
Stopped: `11/4/2022, 8:47:24 UTC`

The tasks that are not being run in parallel are the `datalog-extractor` ones:

**Task 1:**

Created: `11/4/2022, 8:32:35 UTC`
Started: `11/4/2022, 8:33:45 UTC`
Stopped: `11/4/2022, 8:34:16 UTC`

**Task 2:**

Created: `11/4/2022, 8:34:41 UTC`
Started: `11/4/2022, 8:35:44 UTC`
Stopped: `11/4/2022, 8:36:15 UTC`

**Task 3:**

Created: `11/4/2022, 8:36:42 UTC`
Started: `11/4/2022, 8:37:45 UTC`
Stopped: `11/4/2022, 8:38:16 UTC`

...

The last one stopped on `11/4/2022, 8:45:02 UTC`.

We said in the previous comment that the `data-providers` were the tasks spending a lot of time, but after seeing this, we discard that statement and confirm that the `datalog-extractor` tasks are the ones spending the most of the time.

These `datalog-extractor` tasks are run in the `extractDataFromLogs` function and they are not included in a `parallel` block. An issue will be opened in the Wazuh CICD repository to investigate the possibility to run these tasks in parallel. If the tasks cannot be run in parallel, we will not be able to improve these times more. 

With the last conclusion, I suggest that we close this issue in favor of the new one in the CICD repository, as the code making this stage slow has been discovered and investigated.

Also, we have to take into account that there are known limitations in terms of parallelizing this kind of task, but these limitations may not be present here.

**Closed** 2022-04-20 08:08 UTC
Labels: feature/cluster, tool/data-visualization
