### ISSUE TITLE
SCA checks IDs are not unique

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3393] opened 2022-09-30 09:25 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|             4.4.0           |              https://github.com/wazuh/wazuh/issues/14346          |                    |

## Description

There are some YML files using the same id set. This issue will solve this by modifying the conflicting ones.

## Proposed checks

- [x]  Verify in the repository wazuh/wazuh/ branch 4.3 that the YMLs under folder ruleset/sca haven't any id conflict.

**Comment by fedepacher** [comment] 2022-10-27 11:09
# Update 2022/10/26

At this point, it could not find any duplicated `id` in the repository `wazuh/wazuh/` branch `Dup_sca_ids`.
To check this, it has implemented a python script that prints the duplicated ids in the `duplicated_id.txt` file and the path where the ids were found.


<details>
<summary>Python script code</summary>

[check_sca_ids.zip](https://github.com/wazuh/wazuh-qa/files/9878714/check_sca_ids.zip)

</details>

**Comment by fedepacher** [comment] 2022-10-28 12:05
# Testing results :green_circle: 

## Unfixed

<details><summary>Error reproduced</summary>
  
  1. Install `wazuh-manager`
  2. Check IDs in Wazuh manager 4.3.5
     ```
     # /var/ossec/bin/wazuh-control info
     WAZUH_VERSION="v4.3.5"
     WAZUH_REVISION="40317"
     WAZUH_TYPE="server"
     ```
  
     [duplicated_ids.zip](https://github.com/wazuh/wazuh-qa/files/9880996/duplicated_ids.zip)
     
  </details>

## Upgrade

<details><summary>Upgrade process :green_circle:</summary>

  1. Upgrade `wazuh-manager` :green_circle:
     ```
     dpkg -i wazuh-manager_4.4.0-0.commit1abe64d_amd64.deb
     ```
     ``` 
     (Reading database ... 138782 files and directories currently installed.)
     Preparing to unpack wazuh-manager_4.4.0-0.commit1abe64d_amd64.deb ...
     Unpacking wazuh-manager (4.4.0-0.commit1abe64d) over (4.3.5-1) ...
     Setting up wazuh-manager (4.4.0-0.commit1abe64d) ...
     ```
  2. Check IDs in Wazuh manager 4.4.0
     ```
     # /var/ossec/bin/wazuh-control info
     WAZUH_VERSION="v4.4.0"
     WAZUH_REVISION="40400"
     WAZUH_TYPE="server"
     ```
     
     No repeated IDs were found
     
</details>

## Fresh install

<details><summary>Fresh install :green_circle:</summary>

  1. Check IDs in Wazuh manager 4.4.0
     ```
     # /var/ossec/bin/wazuh-control info
     WAZUH_VERSION="v4.4.0"
     WAZUH_REVISION="40400"
     WAZUH_TYPE="server"
     ```
     
     No repeated IDs were found

</details>

**Comment by jmv74211** [comment] 2022-10-28 15:34
## Closing conclusion 👍🏼  

Everything seems to be working properly.

**Closed** 2022-10-28 15:34 UTC
Labels: team/qa, target/4.4.0, type/dev-testing, subteam/qa-main
