### ISSUE TITLE
Fix AWS Cloudwatch integration tests

### ISSUE THREAD

**Issue by nico-stefani** [wazuh/wazuh-qa#4799] opened 2023-12-28 14:06 UTC
## Description

Currently, the integration tests, for the Cloudwatch integration, are broken.

```python
============================= test session starts ==============================
platform linux -- Python 3.10.12, pytest-7.1.2, pluggy-1.3.0
rootdir: /wazuh-qa-4.7.2-rc1/tests/integration, configfile: pytest.ini
plugins: html-3.1.1, metadata-3.0.0, testinfra-5.0.0
collected 198 items / 186 deselected / 12 selected

tests/integration/test_aws/test_basic.py F                               [  8%]
tests/integration/test_aws/test_discard_regex.py FF                      [ 25%]
tests/integration/test_aws/test_log_groups.py FF                         [ 41%]
tests/integration/test_aws/test_only_logs_after.py .FFE                  [ 66%]
tests/integration/test_aws/test_regions.py FF.                           [ 91%]
tests/integration/test_aws/test_remove_from_bucket.py .                  [100%]
=========================== short test summary info ============================
FAILED tests/integration/test_aws/test_basic.py::test_service_defaults[cloudwatchlogs_defaults]
FAILED tests/integration/test_aws/test_discard_regex.py::test_cloudwatch_discard_regex_json[cloudwatch_discard_regex_json]
FAILED tests/integration/test_aws/test_discard_regex.py::test_cloudwatch_discard_regex_simple_text[cloudwatch_discard_regex_simple_text]
FAILED tests/integration/test_aws/test_log_groups.py::test_log_groups[cloudwatchlogs_log_groups_with_data]
FAILED tests/integration/test_aws/test_log_groups.py::test_log_groups[cloudwatchlogs_inexistent_log_group]
FAILED tests/integration/test_aws/test_only_logs_after.py::test_cloudwatch_with_only_logs_after[cloudwatchlogs_with_only_logs_after]
FAILED tests/integration/test_aws/test_only_logs_after.py::test_cloudwatch_multiple_calls[cloudwatchlogs_only_logs_after_multiple_calls]
FAILED tests/integration/test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_region_with_data]
FAILED tests/integration/test_aws/test_regions.py::test_cloudwatch_regions[cloudwatchlogs_regions_with_data]
ERROR tests/integration/test_aws/test_only_logs_after.py::test_cloudwatch_multiple_calls[cloudwatchlogs_only_logs_after_multiple_calls]
======= 9 failed, 3 passed, 186 deselected, 1 error in 413.75s (0:06:53) =======
```

This is because during #4714 some resources, that the tests expected, were deleted.

This issue aims to recreate these resources and modify the dates in certain test cases to work with the new events. By example:

https://github.com/wazuh/wazuh-qa/blob/a4f927b6a2ca349df2625f37c308f0ebee8b3336/tests/integration/test_aws/test_only_logs_after.py#L890-L909

The reason for this is to fix the execution for the next release testing previous to 4.9.0.

**Comment by javiersanchz** [comment] 2024-01-05 18:23
## Update 

- I was launching the integration tests to see the failures, researching the changes to be made and modifying the tests.

**Comment by javiersanchz** [comment] 2024-01-11 17:26
## Update
- I continue making changes to the tests and checking their functionality with some failures

**Comment by javiersanchz** [comment] 2024-01-16 17:57
## Update 
 - I have been changing the parameters of the tests and I keep getting errors when running them.

**Comment by javiersanchz** [comment] 2024-01-17 10:21
## Update 

- After discussing the issue, the decision has been made not to proceed with it since it has already been manually verified at https://github.com/wazuh/wazuh/issues/20722. A[ manual test](https://github.com/wazuh/wazuh/issues/20722#issuecomment-1854410413) of its functionality was conducted on the cloudwatchlogs service, and work is underway at https://github.com/wazuh/wazuh-qa/issues/4714 to generate isolated resources for each AWS integration test. Therefore, there is no need to complete this issue

**Comment by GGP1** [comment] 2024-01-17 12:05
## Review

The failures are caused by a missing log stream in all the tests using AWS Cloudwatch logs. 

As mentioned in the latest update, this is being investigated in https://github.com/wazuh/wazuh-qa/issues/4714 and the corresponding isolated resources for each test will be generated there. 

I believe the conclusion is correct and this issue should be closed in favor of the other one.

**Closed** 2024-01-17 12:56 UTC
Labels: test/integration, level/task, type/bug
