### ISSUE TITLE
Validate implementation auto-defragmentation functionality in wazuh-db 

### ISSUE THREAD

**Issue by QU3B1M** [wazuh/wazuh-qa#3471] opened 2022-10-13 11:46 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|   4.4          |[#12930](https://github.com/wazuh/wazuh/issues/12930)|  https://github.com/wazuh/wazuh/pull/15440 |

## Description

This issue [#14968](https://github.com/wazuh/wazuh/issues/14968) is the second part of the development of [#12930](https://github.com/wazuh/wazuh/issues/12930), it implements the `auto-defragmentation` functionality in `wazuh-db` affecting both the global db and the agent's db. 

## Proposed checks

- [x] Fresh Install - Validate auto-defragmentation functionality
  <details><summary>Test cases</summary>

    - <details><summary>Auto defragmentation works correctly for global db</summary>

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
      </details>
      
    - <details><summary>Auto defragmentation works correctly for global and agent db</summary>

        1. Install wazuh-manager and a wazuh-agent
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global and agent dbs
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent_id>.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent_id>.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
      </details>

    - <details><summary>Auto defragmentation works correctly for global and multiple agents dbs</summary>

        1. Install wazuh-manager and four wazuh-agents
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global and agent dbs
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent1_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent2_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent3_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent4_id>.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step in each db
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value` in each db
      </details>
  </details>

- [x] Fresh Install - Validate warning log
  <details><summary>Test cases</summary>

    - <details><summary>Warning log is raised when current fragmentation is higher than the last one</summary>

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Modify the value of `current_fragmentation` to 0 in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the `current_fragmentation` is higher than the `last_fragmentation_value`
        7. Check the Warning log is raised
            `grep "WARN" /var/ossec/logs/ossec.log`
      </details>

    - <details><summary>Warning log is not raised when current fragmentation is lower than the last one</summary>

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Modify the value of `current_fragmentation` to 100 in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
        7. Check the Warning log is not raised
            `grep "WARN" /var/ossec/logs/ossec.log`
      </details>

    - <details><summary>Warning log is not raised when current fragmentation is equal than the last one</summary>

        > Im not sure that this will works, because we need to ensure that two times we will have the same fragmentation result.

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 30 secconds
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Let the `auto-defragmentation` to be executed 4 times *(wait 2 minutes)*
        4. Check the value of `current_fragmentation` in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the Warning log is not raised
            `grep "WARN" /var/ossec/logs/ossec.log`
      </details>

  </details>
  
- [x] Upgrade - Validate auto-defragmentation functionality
  <details><summary>Test cases</summary>

    - <details><summary>Auto defragmentation works correctly for global db</summary>

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
      </details>
      
    - <details><summary>Auto defragmentation works correctly for global and agent db</summary>

        1. Install wazuh-manager and a wazuh-agent
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global and agent dbs
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent_id>.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent_id>.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
      </details>

    - <details><summary>Auto defragmentation works correctly for global and multiple agents dbs</summary>

        1. Install wazuh-manager and four wazuh-agents
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Check the value of `current_fragmentation` in the global and agent dbs
          `sqlite3 /var/ossec/queue/db/global.db`
          `sqlite3 /var/ossec/queue/db/<agent1_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent2_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent3_id>.db`
          `sqlite3 /var/ossec/queue/db/<agent4_id>.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step in each db
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value` in each db
      </details>
  </details>

- [x] Upgrade - Validate warning log
  <details><summary>Test cases</summary>

    - <details><summary>Warning log is raised when current fragmentation is higher than the last one</summary>

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Modify the value of `current_fragmentation` to 0 in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the `current_fragmentation` is higher than the `last_fragmentation_value`
        7. Check the Warning log is raised
            `grep "WARN" /var/ossec/logs/ossec.log`
      </details>

    - <details><summary>Warning log is not raised when current fragmentation is lower than the last one</summary>

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 2 minutes
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Modify the value of `current_fragmentation` to 100 in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        4. Let the `auto-defragmentation` to be executed *(wait 2 minutes)*
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the `current_fragmentation` is lower than the `last_fragmentation_value`
        7. Check the Warning log is not raised
            `grep "WARN" /var/ossec/logs/ossec.log`
      </details>

    - <details><summary>Warning log is not raised when current fragmentation is equal than the last one</summary>

        > Im not sure that this will works, because we need to ensure that two times we will have the same fragmentation result.

        1. Install wazuh-manager
        2. Configure the `local_internal_options` to execute auto-defragmentation every 30 secconds
            > It could be 1 minute or 3, or any, I used 2 because it is confortable
        3. Let the `auto-defragmentation` to be executed 4 times *(wait 2 minutes)*
        4. Check the value of `current_fragmentation` in the global db
          `sqlite3 /var/ossec/queue/db/global.db`
        5. Check the value of `last_fragmentation_value` is the same than the `current_fragmentation` in the previous step
          `sqlite3 /var/ossec/queue/db/global.db`
        6. Check the Warning log is not raised
            `grep "WARN" /var/ossec/logs/ossec.log`
      </details>

  </details>

## Expected results

The implementation of the new functionality should be successful

**Comment by Rebits** [comment] 2022-11-17 10:55
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 22.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|  [Ubuntu Manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.5/deb/var/wazuh-manager_4.5.0-0.commit976dd09_amd64.deb) | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@vikman)

**Comment by Rebits** [comment] 2022-11-17 17:51
### Update - 17/11/2022
- Meeting with @cborla and @Nicogp 
- Deployment and provision of production and development environments
- Creation of wazuh-db fragmentation script. 68% achieved:
```
root@ip-172-31-23-162:/home/ubuntu# python3 check-db-state.py -f global.db.copy 
DB:global.db.copy 
Fragmentation:68.81 %
Total pages:298 
Free pages:2
```  
- Multiple free pages achieved 
```
root@ip-172-31-23-162:/home/ubuntu# python3 check-db-state.py -f global.db.copy 
DB:global.db.copy 
Fragmentation:0.00 %
Total pages:298 
Free pages:284
```

**Comment by Rebits** [comment] 2022-11-18 11:35
### Update - 18/11/2022
After a meeting with @jmv74211 and @davidjiglesias, we have decided to avoid effort replicating high fragmentation rates for this issue. Instead, we are going to use an already provided fragmented database:
```
DB:/var/ossec/queue/db/global.db 
Fragmentation:99.01 %
Total pages:41992 
Free pages:7633`
```

**Comment by Rebits** [comment] 2022-11-21 15:26
### Update - 21/11/2022

<details>

<summary> Bug application </summary>

<br>

Due to the difficulties in bug replication, it has been decided in a meeting with @davidjiglesias and @jmv74211, that we will not replicate the bug in a production environment. Instead, we will ensure that fragmentation is lower after vacuum and the consistency of the database.


</details>

**Comment by Rebits** [comment] 2022-11-22 18:36
### Update - 22/11/2022
- Worked in the script to fragmentation script for agent.db 
- Replicated high fragmented database
- Performed single agent vacuum manual testing
- Performed multiple agent vacuum manual testing
- Performed validate warning log manual testing

**Comment by Rebits** [comment] 2022-11-28 10:41
### Update - 28/11/2022
- Dependencies were updated, unblocking the testing of the following cases:
  - Upgrade - Validate auto-defragmentation functionality
  - Upgrade - Validate warning log

**Comment by Rebits** [comment] 2022-11-28 11:23
### Testing results :red_circle: 

<details>

<summary> Installation error :red_circle:  </summary>

```
root@ip-172-31-20-147:/home/ubuntu/new# apt-get install wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb
E: Couldn't find any package by glob 'wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb'
E: Couldn't find any package by regex 'wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb'
root@ip-172-31-20-147:/home/ubuntu/new# apt-get install ./wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'wazuh-manager' instead of './wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb'
Suggested packages:
  expect
The following NEW packages will be installed:
  wazuh-manager
0 upgraded, 1 newly installed, 0 to remove and 28 not upgraded.
Need to get 0 B/122 MB of archives.
After this operation, 467 MB of additional disk space will be used.
Get:1 /home/ubuntu/new/wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb wazuh-manager amd64 4.4.0-0.commit5f1a447 [122 MB]
Selecting previously unselected package wazuh-manager.
(Reading database ... 100170 files and directories currently installed.)
Preparing to unpack .../wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb ...
Unpacking wazuh-manager (4.4.0-0.commit5f1a447) ...
Setting up wazuh-manager (4.4.0-0.commit5f1a447) ...
dpkg: error processing package wazuh-manager (--configure):
 installed wazuh-manager package post-installation script subprocess returned error exit status 1
Errors were encountered while processing:
 wazuh-manager
needrestart is being skipped since dpkg has failed
N: Download is performed unsandboxed as root as file '/home/ubuntu/new/wazuh-manager_4.4.0-0.commit5f1a447_amd64.deb' couldn't be accessed by user '_apt'. - pkgAcquire::Run (13: Permission denied)
E: Sub-process /usr/bin/dpkg returned an error code (1)
```


</details>

**Comment by Rebits** [comment] 2022-11-29 11:15
### Update - 29/11/2022
- Dependencies are upgraded. I proceed wit the upgrade test cases.

**Comment by jmv74211** [comment] 2022-11-30 11:13
## Closing conclusion 👍🏼

Everything seems to be working properly.

**Disclaimer**: For this DEV testing we have not performed performance tests as such, but we have tested that the new functionality complies with the expected behavior.

It has been tested that `Vacuum` is automatically triggered in both `global.db` and `agent.db` when fragmentation exceeds configurable limits.

**Closed** 2022-11-30 11:36 UTC
Labels: team/qa, target/4.4.0, type/dev-testing, role/qa-binary-beats, subteam/qa-main
