### ISSUE TITLE
Inaccurate macOS display name 

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#3363] opened 2022-09-23 23:52 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4|wazuh/wazuh#14729 |wazuh/wazuh#14822|

## Description
This issue aims to request Manual testing on PR wazuh/wazuh#14822.

**Short problem description**: some macOS OS versions (from Sierra <oldest Wazuh support> to Catalina) show themselves (in the default OS information tool) as `MacOS X`, while their proper name is `macOS`. This inaccurate OS name is affecting both OS inventory information and Manager's agent list information. [Analysis](https://github.com/wazuh/wazuh/issues/14729#issuecomment-1239632323)
### Changes

- **Short problem proposed solution**: change default tool `sw_vers` to `system_profiler` to internally retrieve OS name
  - Change inventory retrieving module (syscollector module) key component (sysinfo/data_provider library) responsible for retrieving OS information. **THIS CODE IS ONLY COMPILED AND USED ON MACOS SYSTEMS**. 
  - Change **agent side** mechanism responsible for updating agent information on the manager (wazuh-agentd' keepalive) 

- **Known/considered scope**
  - Agent inventory (OS)
  - Agent information stored on the Manager agent list
  - Vuln detector: **our research** indicate that VD is not affected by proposed changes

## Steps to reproduce
- Install Wazuh agent on any macOS system from Sierra to the last supported one (there's no official information from Wazuh side. @tsarquis88 test on Monterrey )

## Results before changes
- Wazuh Manager show, in every possible data interface (like API, Dashboard, Manager's CLI tools) `MacOS X` as OS name from Sierra to Catalina, and `macOS` from BigSur to the last supported one 

## Results after changes
- Wazuh Manager show, in every possible data interface (like API, Dashboard, Manager's CLI tools) `macOS` as OS name from Sierra to the last supported one 

## Test cases

- Reproduce the error in production (Manager 4.3.8 - Agents 4.3.8)
  <details><summary><b>Check the OS name in [Dashboard]</b></summary>

    <br>

    - Overview > Integrity monitoring
    - Agents overview
    - Inventory data
  </details>
  <details><summary><b>Check the OS name in [API]</b></summary>

    <br>

    - Get agent OS
    - List agents (filter by os name)
    - Get agents overview
    - Delete agents (filter by os name)
    - Get agents in a group (filter by os name)
    - List agents distinct
    - Summarize agents OS
    - Upgrade agents
    - Get upgrade results
  </details>
  <details><summary><b>Check the OS name in [Manager Database]</b></summary>

    <br>

    - Query the manager database to get information about the agent
  </details>

- Upgrade to the fixed version (Manager 4.3.8 -> 4.4.0 | Agents 4.3.8 -> 4.4.0)
    - Upgrade agent through WPK
    - Check the OS name in [Dashboard]
    - Check the OS name in [API]
    - Check the OS name in [Manager Database]
 
- Fresh install (Manager 4.4.0 - Agents 4.4.0)
    - Check the OS name in [Dashboard]
    - Check the OS name in [API]
    - Check the OS name in [Manager Database]

**Comment by mauromalara** [comment] 2022-09-26 23:04
## Review data

| Tester | PR commit               | 
|--------|-------------------------|
| @mauromalara |  [667da4f](https://github.com/wazuh/wazuh/pull/14822/commits/667da4fb853677b5f95995e4d746cc1544500ba6) | 

### Testing environment

| OS | OS version | Deployment | Image/AMI | Notes
|-- |-- |-- |-- |--
| macOS

### Tested packages

| OS | Prod | Dev branch
|-- |-- |--
| macOS

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved
- [ ] QA manager approved
- [ ] Development team leader approved

### Conclusion 🔵

WIP.

**Comment by mauromalara** [comment] 2022-09-28 20:29
## macOS Sierra

### Reproduce the error in production (Manager 4.3.8 - Agents 4.3.8)

<details><summary><b>Check the OS name in [Dashboard]</b></summary>
  <br>
  - Overview > Integrity monitoring
  - Agents overview
  - Inventory data
</details>
<details><summary><b>Check the OS name in [API]</b></summary>
  <br>
  - Get agent OS
  - List agents (filter by os name)
  - Get agents overview
  - Delete agents (filter by os name)
  - Get agents in a group (filter by os name)
  - List agents distinct
  - Summarize agents OS
  - Upgrade agents
  - Get upgrade results
</details>
<details><summary><b>Check the OS name in [Manager Database]</b></summary>
  <br>
  - Query the manager database to get information about the agent
</details>

### Upgrade to the fixed version (Manager 4.3.8 -> 4.4.0 | Agents 4.3.8 -> 4.4.0)

<details><summary><b>Upgrade agent through WPK</b></summary></details>
<details><summary><b>Check the OS name in [Dashboard]</b></summary>
  <br>
  - Overview > Integrity monitoring
  - Agents overview
  - Inventory data
</details>
<details><summary><b>Check the OS name in [API]</b></summary>
  <br>
  - Get agent OS
  - List agents (filter by os name)
  - Get agents overview
  - Delete agents (filter by os name)
  - Get agents in a group (filter by os name)
  - List agents distinct
  - Summarize agents OS
  - Upgrade agents
  - Get upgrade results
</details>
<details><summary><b>Check the OS name in [Manager Database]</b></summary>
  <br>
  - Query the manager database to get information about the agent
</details>

### Fresh install (Manager 4.4.0 - Agents 4.4.0)

<details><summary><b>Check the OS name in [Dashboard]</b></summary>
  <br>
  - Overview > Integrity monitoring
  - Agents overview
  - Inventory data
</details>
<details><summary><b>Check the OS name in [API]</b></summary>
  <br>
  - Get agent OS
  - List agents (filter by os name)
  - Get agents overview
  - Delete agents (filter by os name)
  - Get agents in a group (filter by os name)
  - List agents distinct
  - Summarize agents OS
  - Upgrade agents
  - Get upgrade results
</details>
<details><summary><b>Check the OS name in [Manager Database]</b></summary>
  <br>
  - Query the manager database to get information about the agent
</details>

**Comment by mauromalara** [comment] 2022-09-28 21:13
## macOS Monterey

### Upgrade to the fixed version (Manager 4.3.8 -> 4.4.0 | Agents 4.3.8 -> 4.4.0)

<details><summary><b>Upgrade agent through WPK</b></summary></details>
<details><summary><b>Check the OS name in [Dashboard]</b></summary>

  <br>

  - Modules > Integrity monitoring (No agent selected)
  - Agents overview
  - Inventory data
</details>
<details><summary><b>Check the OS name in [API]</b></summary>

  <br>

  - Get agent OS
  - List agents (filter by os name)
  - Get agents overview
  - Delete agents (filter by os name)
  - Get agents in a group (filter by os name)
  - List agents distinct
  - Summarize agents OS
  - Upgrade agents
  - Get upgrade results
</details>
<details><summary><b>Check the OS name in [Manager Database]</b></summary>

  <br>

  - Query the manager database to get information about the agent
</details>

### Fresh install (Manager 4.4.0 - Agents 4.4.0)

<details><summary><b>Check the OS name in [Dashboard]</b></summary>

  <br>

  - Modules > Integrity monitoring (No agent selected)
  - Agents overview
  - Inventory data
</details>
<details><summary><b>Check the OS name in [API]</b></summary>

  <br>

  - Get agent OS
  - List agents (filter by os name)
  - Get agents overview
  - Delete agents (filter by os name)
  - Get agents in a group (filter by os name)
  - List agents distinct
  - Summarize agents OS
  - Upgrade agents
  - Get upgrade results
</details>
<details><summary><b>Check the OS name in [Manager Database]</b></summary>

  <br>

  - Query the manager database to get information about the agent
</details>

**Comment by jmv74211** [comment] 2022-10-20 09:45
## QA review

- **Type**: Manual testing.
- **Status**: Requested improvements 🟡 
- **Comments**: Some issues have been detected that appear to be unrelated to the changes being tested. These are as follows:
    - ***(1)* Error when upgrading a macOS agent through WPK. (cc @wazuh/drop-table)**

        During manual testing, a segmentation fault message (from modulesd) appears, this happens after attempting an upgrade through WPK (from `4.3.8` to `4.4.0` using branch: `14729-macos-invalid-os-name`)

    - **_(2)_ The dashboard does not show correctly the name of the OS (cc @wazuh/frontend)**.  


This will be discussed with the development team, and the PR will be approved or not on this basis.

**Comment by jmv74211** [comment] 2022-10-20 10:04
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 

The development has been approved taking into account the following considerations proposed in the [QA review](https://github.com/wazuh/wazuh-qa/issues/3363#issuecomment-1285242133):

***(1)*: Error when upgrading a macOS agent through WPK. (cc @wazuh/drop-table)** 🔵 

This will be investigated and fixed in further developments. Reported issue [wazuh#15081](https://github.com/wazuh/wazuh/issues/15081).

***(2)*: The dashboard does not show correctly the name of the OS** 🔵 

Due to we don't officially have a wazuh-dashboard app for `4.4.0` where test it, we have decided to open a new release testing issue, to check this in `pre-release` stage. Here is the new release testing issue [wazuh-qa#3494](https://github.com/wazuh/wazuh-qa/issues/3494).

**Closed** 2022-10-21 07:31 UTC
Labels: team/qa, target/4.4.0, type/dev-testing, role/qa-drop-table, subteam/qa-rainbow
