### ISSUE TITLE
`Failed to disable unit: Unit file wazuh-manager.service does not exist` message was found during manager testing 

### ISSUE THREAD

**Issue by pro-akim** [wazuh/wazuh-qa#5742] opened 2024-09-17 09:45 UTC
| Target version | Related issue | Related PR/dev branch |
|---|---|---|
| 4.9.0  | https://github.com/wazuh/wazuh/issues/23748  | https://github.com/wazuh/wazuh-qa/pull/5689  |

The message:

```
�[0;33m    Failed to disable unit: Unit file wazuh-manager.service does not exist.�[0m
```

It was found during manager testing in deployability tests (uninstall process).

It does not interfere with the tests themselves, but its nature should be investigated.

**Comment by joaquinsgi** [comment] 2024-09-18 18:07
We will attempt to replicate this behavior using `Test-manager-complete.yaml`.

**Comment by joaquinsgi** [comment] 2024-09-19 16:31
The behavior has been replicated, now the `test_uninstall.py` code will be investigated. Although the test was successful

It will be attempted to replicate the behavior locally, following each of the steps in `test_uninstall.py`

**Comment by joaquinsgi** [comment] 2024-09-20 15:12
The error has been reproduced, and it has been shown that it is due to running the `systemctl disable wazuh-manager` command after previously uninstalling with the `--purge` option, which results in the error mentioned in the issue.
![failed](https://github.com/user-attachments/assets/c3eee456-4f04-4e99-9a52-67a54e54e7af)

After speaking with @rauldpm, the `systemctl disable wazuh-manager` command will be removed since it was the cause of the error. Since a remove with the `--purge` option is performed earlier, the uninstallation will be successful, and there will be no need to run the disable command. These changes will be made and tested in the development branch:
- https://github.com/wazuh/wazuh-qa/tree/bug/5742-failed-manager-not-exist

After relaunching the job flow with the described changes, and since no errors appeared and it was successful, a pull request has been created to merge the changes.
Log:
[jobflow.log](https://github.com/user-attachments/files/17079242/jobflow.log)

- https://github.com/wazuh/wazuh-qa/pull/5761

**Comment by joaquinsgi** [comment] 2024-09-25 15:51
A new development branch has been created to introduce the changes into `4.10.0`
- https://github.com/wazuh/wazuh-qa/tree/bug/5742-failed-to-disable-manager.

A new Pull request has been created to merge the change.
- https://github.com/wazuh/wazuh-qa/pull/5775

**Comment by hossam1522** [comment] 2024-09-25 17:56
LGTM!

**Comment by joaquinsgi** [comment] 2024-09-26 14:58
In order to update the Uninstalling Documentation for manager, a new isssue has been created:
- https://github.com/wazuh/wazuh-documentation/issues/7808

**Closed as completed** 2024-09-27 14:49 UTC
Labels: level/task, type/bug
