### ISSUE TITLE
Failed System test test_agent_key_polling in 4.8.0 Beta 2

### ISSUE THREAD

**Issue by Deblintrake09** [wazuh/wazuh-qa#5030] opened 2024-02-26 17:58 UTC
## Description

During the testing in [Release 4.8.0 - Beta 2 - System tests](https://github.com/wazuh/wazuh/issues/22123), an error has been encountered in the basic_cluster environment, specifically in this test: `test_cluster/test_agent_key_polling/test_agent_key_polling.py::test_agent_key_polling`.

The test was executed in a Ubuntu 22.04.2 LTS C5.XLarge 15GB SSD instance, provided by the devops team.

## Current behavior

<details><summary>Error details</summary>

```
def test_agent_key_polling():
        """Check that the agent key polling cycle works correctly. To do this, we use the messages and the hosts defined
        in data/messages.yaml and the hosts inventory.
    
        Parameters
        ----------
        inventory_path : str
            Path to the Ansible hosts inventory
        """
        actual_path = os.path.dirname(os.path.abspath(__file__))
        configure_environment(host_manager)
    
        host_monitor = HostMonitor(inventory_path=inventory_path,
                                   messages_path=os.path.join(actual_path, 'data/messages.yaml'),
                                   tmp_path=os.path.join(actual_path, 'tmp'))
>       host_monitor.run()

test_cluster/test_agent_key_polling/test_agent_key_polling.py:62: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/usr/local/lib/python3.10/dist-packages/wazuh_testing-4.8.0-py3.10.egg/wazuh_testing/tools/system_monitoring.py:94: in run
    self.check_result()
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <wazuh_testing.tools.system_monitoring.HostMonitor object at 0x7fbf04b39690>

    def check_result(self):
        """Check if a TimeoutError occurred."""
        logger.debug('Checking results...')
        while not self._queue.empty():
            result = self._queue.get(block=True)
            for host, msg in result.items():
                if isinstance(msg, TimeoutError):
>                   raise msg
E                   TimeoutError: Did not found the expected callback in wazuh-master: .*Agent key generated for agent 'wazuh-agent2'.*

/usr/local/lib/python3.10/dist-packages/wazuh_testing-4.8.0-py3.10.egg/wazuh_testing/tools/system_monitoring.py:179: TimeoutError
 ------------------------------Captured stderr call------------------------------ 
2024-02-26 16:34:59,590 - wazuh_testing - DEBUG - Add new file composer process for wazuh-master and path: /var/ossec/logs/ossec.log
2024-02-26 16:34:59,595 - wazuh_testing - DEBUG - Starting file composer for wazuh-master and path: /var/ossec/logs/ossec.log. Composite file in /home/ubuntu/wazuh-qa/tests/system/test_cluster/test_agent_key_polling/tmp/wazuh-master_ossec.log.tmp
2024-02-26 16:34:59,596 - wazuh_testing - DEBUG - Add new file monitor process for wazuh-master and path: /var/ossec/logs/ossec.log
2024-02-26 16:34:59,604 - wazuh_testing - DEBUG - Add new file composer process for wazuh-worker1 and path: /var/ossec/logs/ossec.log
2024-02-26 16:34:59,611 - wazuh_testing - DEBUG - Starting QueueMonitor for wazuh-master and message: .*Agent key generated for agent 'wazuh-agent2'.*
2024-02-26 16:34:59,614 - wazuh_testing - DEBUG - Starting file composer for wazuh-worker1 and path: /var/ossec/logs/ossec.log. Composite file in /home/ubuntu/wazuh-qa/tests/system/test_cluster/test_agent_key_polling/tmp/wazuh-worker1_ossec.log.tmp
2024-02-26 16:34:59,610 - wazuh_testing - DEBUG - Add new file monitor process for wazuh-worker1 and path: /var/ossec/logs/ossec.log
2024-02-26 16:34:59,622 - wazuh_testing - DEBUG - Add new file composer process for wazuh-agent2 and path: /var/ossec/logs/ossec.log
2024-02-26 16:34:59,629 - wazuh_testing - DEBUG - Starting QueueMonitor for wazuh-worker1 and message: .*Agent key generated for 'wazuh-agent2'.*
2024-02-26 16:34:59,635 - wazuh_testing - DEBUG - Add new file monitor process for wazuh-agent2 and path: /var/ossec/logs/ossec.log
2024-02-26 16:34:59,646 - wazuh_testing - DEBUG - Starting QueueMonitor for wazuh-agent2 and message: .*Lost connection with manager. Setting lock.*
2024-02-26 16:34:59,650 - wazuh_testing - DEBUG - Starting file composer for wazuh-agent2 and path: /var/ossec/logs/ossec.log. Composite file in /home/ubuntu/wazuh-qa/tests/system/test_cluster/test_agent_key_polling/tmp/wazuh-agent2_ossec.log.tmp
2024-02-26 16:36:29,668 - wazuh_testing - DEBUG - Finishing QueueMonitor for wazuh-master and message: .*Agent key generated for agent 'wazuh-agent2'.*
2024-02-26 16:36:29,684 - wazuh_testing - DEBUG - Finishing QueueMonitor for wazuh-worker1 and message: .*Agent key generated for 'wazuh-agent2'.*
2024-02-26 16:36:29,764 - wazuh_testing - DEBUG - Finishing QueueMonitor for wazuh-agent2 and message: .*Lost connection with manager. Setting lock.*
2024-02-26 16:36:29,764 - wazuh_testing - DEBUG - Starting QueueMonitor for wazuh-agent2 and message: .*Trying to connect to server \(\[wazuh-worker1.*
2024-02-26 16:37:59,891 - wazuh_testing - DEBUG - Finishing QueueMonitor for wazuh-agent2 and message: .*Trying to connect to server \(\[wazuh-worker1.*
2024-02-26 16:37:59,891 - wazuh_testing - DEBUG - Starting QueueMonitor for wazuh-agent2 and message: .*Connected to the server \(\[wazuh-worker1.*
2024-02-26 16:39:30,011 - wazuh_testing - DEBUG - Finishing QueueMonitor for wazuh-agent2 and message: .*Connected to the server \(\[wazuh-worker1.*
2024-02-26 16:39:30,215 - wazuh_testing - DEBUG - Cleaning temporal files...
2024-02-26 16:39:30,239 - wazuh_testing - DEBUG - Checking results...

 -------------------------------Captured log call-------------------------------- 
DEBUG    wazuh_testing:system_monitoring.py:78 Add new file composer process for wazuh-master and path: /var/ossec/logs/ossec.log
DEBUG    wazuh_testing:system_monitoring.py:82 Add new file monitor process for wazuh-master and path: /var/ossec/logs/ossec.log
DEBUG    wazuh_testing:system_monitoring.py:78 Add new file composer process for wazuh-worker1 and path: /var/ossec/logs/ossec.log
DEBUG    wazuh_testing:system_monitoring.py:82 Add new file monitor process for wazuh-worker1 and path: /var/ossec/logs/ossec.log
DEBUG    wazuh_testing:system_monitoring.py:78 Add new file composer process for wazuh-agent2 and path: /var/ossec/logs/ossec.log
DEBUG    wazuh_testing:system_monitoring.py:82 Add new file monitor process for wazuh-agent2 and path: /var/ossec/logs/ossec.log
DEBUG    wazuh_testing:system_monitoring.py:185 Cleaning temporal files...
DEBUG    wazuh_testing:system_monitoring.py:174 Checking results...
```

</details>

## Expected results

All the tests should be passed

Report: [basic_cluster.zip](https://github.com/wazuh/wazuh/files/14408688/basic_cluster.zip)

**Comment by rauldpm** [comment] 2024-02-29 21:32
Related https://github.com/wazuh/wazuh-qa/issues/2044 (2021)

**Comment by juliamagan** [comment] 2024-03-05 17:02
The error could not be reproduced locally. We have tried changing the instance type in AWS from c5.xlarge to c5a.xlarge and the test has not failed either, but it needs more executions and investigation to check if this could fix the problem with system tests in virtual environments.

[ec2-report.zip](https://github.com/wazuh/wazuh-qa/files/14498822/ec2-report.zip)
[report2.zip](https://github.com/wazuh/wazuh-qa/files/14498824/report2.zip)
[report1.zip](https://github.com/wazuh/wazuh-qa/files/14498825/report1.zip)

**Comment by juliamagan** [comment] 2024-03-06 13:47
After several runs, the error could not be reproduced. Another test failed when waiting for the agent status, but as we can see it has nothing to do with the instance type. 

|c5.xlarge|c5a.xlarge|
|:--:|:--:|
| [🟢 ](https://github.com/wazuh/wazuh-qa/files/14510648/c5_evidences1.zip)|[🟢 ](https://github.com/wazuh/wazuh-qa/files/14510664/c5a_evidences1.zip)|
|[🔴 ](https://github.com/wazuh/wazuh-qa/files/14510651/c5_evidences2.zip)  |[🟢 ](https://github.com/wazuh/wazuh-qa/files/14510669/c5a_evidences2.zip)
|
|[🟢 ](https://github.com/wazuh/wazuh-qa/files/14510653/c5_evidences3.zip) |[🔴 ](https://github.com/wazuh/wazuh-qa/files/14510672/c5a_evidences3.zip) |


I propose to close this issue since the system tests are flaky and need a refactor. Also, for future occasions, I would check in the test reports if the log that says not found, appears or not, and if it appears, mark it as a known issue.

**Comment by rafabailon** [comment] 2024-03-06 14:02
### LGTM

**Comment by davidjiglesias** [comment] 2024-03-08 07:03
LGTM

**Closed by davidjiglesias** 2024-03-08 07:03 UTC
Labels: level/task, type/bug
