### ISSUE TITLE
Fix defects found by Coverity in 4.4.0-alpha1

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3654] opened 2022-12-07 08:40 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4.0|https://github.com/wazuh/wazuh/issues/15556|https://github.com/wazuh/wazuh/pull/15573|

## Description

This PR aims to fix the defects described in https://github.com/wazuh/wazuh/issues/15556.

The changes affect the following components:

- Wazuh DB.
- Database synchronization module (_client.keys_ → Wazuh DB).
- FIM (`<prefilter_cmd>`).
- Key polling module in Authd (innocuous).

## Proposed checks

- [x] Synchronize _client.keys_ with an existing database at _var/db_ (see PR).
- [x] Run an FIM scan with `<prefilter_cmd>`.
- [x] Poll a key.

## Configuration and considerations

- Remember that `<prefilter_cmd>` requires a full path to an executable file.

**Comment by Rebits** [comment] 2022-12-12 10:41
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/15573/commits/fe217c52b4b6bf6aaa877cd849117cfed7dc86ec | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|  [wazuh-manager](https://packages-dev.wazuh.com/warehouse/pullrequests/4.4/deb/var/wazuh-agent_4.4.0-0.commitfe217c5_amd64.deb)  | 

### Status

- [x] In progress
- [ ] Pending Review
-  [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@vikman90 )

**Comment by Rebits** [comment] 2022-12-12 10:43
### Testing results


<details>

<summary> Synchronize <code>_client.keys_</code> with an existing database at <code>_var/db_</code> :large_blue_circle:</summary>

</details>

<details>

<summary>  Run an FIM scan with <code>prefilter_cmd</code> :large_blue_circle: </summary>

</details>



<details>

<summary>Poll a key  :large_blue_circle: </summary>

</details>

**Comment by Rebits** [comment] 2022-12-12 17:08
### Update 12/12/2022
- Perform the `Synchronize _client.keys_ with an existing database at _var/db_` test case
- Perform the `Run an FIM scan with prefilter_cmd` test case
- Perform `Poll a key - Single node` test case
- Meeting with @MarcelKemp regarding `Poll a key` test case
- Pending `Poll a key - Multi node` testing

**Comment by Rebits** [comment] 2022-12-14 16:40
### Update 14/12/2022
- Work in Multi-Node checks
- Meeting with @MarcelKemp

**Comment by Rebits** [comment] 2022-12-15 16:44
### Update 15/12/2022
- Meeting with @vikman90 and @jmv74211
   - Wrong validation of the ` Corrupt key` case for key polling. Authd should not be running. It is required to repeat these tests cases
   -  It is necessary to ensure wazuh-db reported error does not occur in `4.4`

**Comment by Rebits** [comment] 2022-12-16 12:24
### Update 16/12/2022

## Corrupt key case

All tests have been repeated for 4.4 and for development. We can conclude the following:

- Previously detected wazuh-db and wash-analysis errors are present also in the `4.4` version. 
Those errors are reproducible in single and multiple nodes for the corrupted key case, but only when the enrollment force option is set as follows:

```
    <force>
      <enabled>yes</enabled>
      <key_mismatch>yes</key_mismatch>
      <disconnected_time enabled="no">1h</disconnected_time>
      <after_registration_time>0</after_registration_time>
    </force>

```
Otherwise, in case of different force configurations, the corrupted key is never fixed:
```
2022/12/16 12:15:04 wazuh-authd[80916] main-server.c:578 at run_dispatcher(): INFO: New connection from 172.31.13.110
2022/12/16 12:15:04 wazuh-authd[80916] main-server.c:606 at run_dispatcher(): ERROR: SSL Error (0)
2022/12/16 12:15:04 wazuh-authd[80916] key_request.c:360 at key_request_dispatch(): DEBUG: Exec output: {"error": 0, "data": {"id": "008", "name": "testing3", "ip": "any", "key": "166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426"}}

2022/12/16 12:15:04 wazuh-authd[80916] key_request.c:401 at key_request_dispatch(): DEBUG: Requesting local addition for agent '008' from the agent key request.
2022/12/16 12:15:04 wazuh-authd[80916] local-server.c:359 at local_add(): DEBUG: add(testing3)
2022/12/16 12:15:04 wazuh-authd[80916] local-server.c:375 at local_add(): WARNING: Duplicate ID, rejecting enrollment. Agent '008' has not been disconnected long enough to be replaced.
2022/12/16 12:15:04 wazuh-authd[80916] key_request.c:406 at key_request_dispatch(): DEBUG: Agent key request addition response: '{"error":9012,"message":"Duplicate ID"}'
2022/12/16 12:15:09 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '008' at 'any'.
2022/12/16 12:15:09 wazuh-remoted: WARNING: Decrypt the message fail, socket 13
2022/12/16 12:15:09 wazuh-authd[80916] key_request.c:360 at key_request_dispatch(): DEBUG: Exec output: {"error": 0, "data": {"id": "008", "name": "testing3", "ip": "any", "key": "166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426"}}
```
> This was achieved, by setting the agent_name in the agent's configuration, in order to avoid it from requesting a new key.

**client.key**:
```
008 testing3 any Testing
```



<details>

<summary> Single Node -  Corrupt key - Development :yellow_circle: </summary>


As in the first iteration, unexpected wazuh-db error appears:
```
2022/12/16 09:15:44 wazuh-db: ERROR: There was an error assigning the groups to agent '005'
```

#### Steps to reproduce


- Configure an single-node environment with an agent active. This agent should be also included in the integrated database

```
root@ip-172-31-0-137:/home/qa# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-0-137 (server), IP: 127.0.0.1, Active/Local
   ID: 006, Name: testing2, IP: any, Active
```  

```
mysql> SELECT * from agent;
+------+----------+------+------------------------------------------------------------------+
| id   | name     | ip   | agent_key                                                        |
+------+----------+------+------------------------------------------------------------------+
| 006  | testing2 | any  | 166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426 |
+------+----------+------+------------------------------------------------------------------+
1 rows in set (0.00 sec)
```
- Stop the wazuh-manager
- Stop the wazuh-agent
- Corrupt the manager's `client.key`
```
006 testing2 any TESTING
```
- Restart the manager
- Restart the agent
- Check that the agent was registered
- Check the ossec.log. Notice that some wazuh-db error appears.  
Also the agent's status is marked as `Unknown` even if the agent is active. The client keys were restored correctly:
```
root@ip-172-31-0-137:/home/qa# cat /var/ossec/etc/client.keys 
006 testing2 any 166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426
```

<details>

<summary> ossec.log </summary>


```
2022/12/16 09:31:37 wazuh-authd[62732] local-server.c:373 at local_add(): INFO: Duplicate ID. Removing old agent 'testing2' (id '006').
2022/12/16 09:31:37 wazuh-authd[62732] local-server.c:439 at local_add(): INFO: Agent key generated for agent 'testing2' (requested locally)
2022/12/16 09:31:37 wazuh-authd[62732] key_request.c:406 at key_request_dispatch(): DEBUG: Agent key request addition response: '{"error":0,"data":{"id":"006","name":"testing2","ip":"any","key":"166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426"}}'
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:828 at run_writer(): DEBUG: Dumping changes into disk.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:850 at run_writer(): DEBUG: [Writer] OS_WriteKeys(): 193 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:860 at run_writer(): DEBUG: [Writer] OS_WriteTimestamps(): 117 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:868 at run_writer(): DEBUG: [Writer] Performing insert([006] testing2).
2022/12/16 09:31:37 wazuh-authd[62732] wdb_global_helpers.c:96 at wdb_insert_agent(): DEBUG: Global DB Error reported in the result of the query
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:872 at run_writer(): DEBUG: The agent 006 'testing2' already exists in the database.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:875 at run_writer(): DEBUG: [Writer] wdb_insert_agent(): 484 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:890 at run_writer(): DEBUG: [Writer] wdb_set_agent_groups_csv(): 0 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:907 at run_writer(): DEBUG: [Writer] Performing delete([006] testing2).
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:912 at run_writer(): DEBUG: [Writer] delete_agentinfo(): 115 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:917 at run_writer(): DEBUG: [Writer] OS_RemoveCounter(): 3 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:922 at run_writer(): DEBUG: [Writer] OS_RemoveAgentTimestamp(): 79 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:929 at run_writer(): DEBUG: [Writer] wdb_remove_agent(): 328 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:935 at run_writer(): DEBUG: [Writer] wdbc_query_ex(): 64 µs.
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:948 at run_writer(): DEBUG: [Writer] Inserted agents: 1
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:949 at run_writer(): DEBUG: [Writer] Removed agents: 1
2022/12/16 09:31:37 wazuh-authd[62732] main-server.c:950 at run_writer(): DEBUG: [Writer] Loop: 3 ms.
2022/12/16 09:31:40 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/12/16 09:31:40 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2022/12/16 09:31:41 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2022/12/16 09:31:42 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2022/12/16 09:31:42 sca: INFO: Security Configuration Assessment scan finished. Duration: 9 seconds.
2022/12/16 09:31:42 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:31:51 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:31:54 rootcheck: INFO: Ending rootcheck scan.
2022/12/16 09:32:01 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:32:11 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:32:21 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:32:32 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:32:42 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:32:52 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
2022/12/16 09:33:02 wazuh-db: ERROR: There was an error assigning the groups to agent '006'
```

</details>

In oder iteration of this checks, also appears an analysisd error:

```
2022/12/16 09:54:55 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:54:58 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 09:54:58 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 09:54:58 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 09:54:58 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 09:55:04 rootcheck: INFO: Ending rootcheck scan.
2022/12/16 09:55:05 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:55:15 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:55:24 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:55:34 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:55:44 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:55:54 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:56:04 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:56:14 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:56:24 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:56:34 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:56:44 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 09:56:55 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
...
```  


</details>


<details>

<summary> Single Node -  Corrupt key - 4.4 :yellow_circle: </summary>


Same wazuh-db and wazuh-analysid error appears:
```
2022/12/16 11:55:48 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 11:55:48 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 11:55:55 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:56:05 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
```

#### Steps to reproduce


- Configure an single-node environment with an agent active. This agent should be also included in the integrated database

```
root@ip-172-31-0-137:/home/qa# /var/ossec/bin/agent_control -l

Wazuh agent_control. List of available agents:
   ID: 000, Name: ip-172-31-0-137 (server), IP: 127.0.0.1, Active/Local
   ID: 008, Name: testing2, IP: any, Active
```  

```
+------+----------+------+------------------------------------------------------------------+
| id   | name     | ip   | agent_key                                                        |
+------+----------+------+------------------------------------------------------------------+
| 008  | testing3 | any  | 166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426 |
+------+----------+------+------------------------------------------------------------------+
1 row in set (0.00 sec)
```
- Stop the wazuh-manager
- Stop the wazuh-agent
- Corrupt the manager's `client.key`
```
008 testing2 any TESTING
```
- Restart the manager
- Restart the agent
- Check that the agent was registered
- Check the ossec.log. Notice that some wazuh-db error appears.  
Also the agent's status is marked as `Unknown` even if the agent is active. The client keys were restored correctly:
```
root@ip-172-31-0-137:/home/qa# cat /var/ossec/etc/client.keys 
008 testing2 any 166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426
```

<details>

<summary> ossec.log </summary>


```
2022/12/16 11:55:40 wazuh-remoted: WARNING: (1404): Authentication error. Wrong key or corrupt payload. Message received from agent '008' at 'any'.
2022/12/16 11:55:40 wazuh-remoted: WARNING: Decrypt the message fail, socket 12
2022/12/16 11:55:40 wazuh-authd: INFO: Duplicate ID. Removing old agent 'testing3' (id '008').
2022/12/16 11:55:40 wazuh-authd: INFO: Agent key generated for agent 'testing3' (requested locally)
2022/12/16 11:55:41 wazuh-syscheckd: INFO: (6009): File integrity monitoring scan ended.
2022/12/16 11:55:41 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/12/16 11:55:41 wazuh-remoted: INFO: (1410): Reading authentication keys file.
2022/12/16 11:55:42 sca: INFO: Evaluation finished for policy '/var/ossec/ruleset/sca/cis_ubuntu22-04.yml'
2022/12/16 11:55:42 sca: INFO: Security Configuration Assessment scan finished. Duration: 7 seconds.
2022/12/16 11:55:45 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:55:48 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 11:55:48 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 11:55:48 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 11:55:48 wazuh-analysisd: ERROR: Error querying policy monitoring database for agent '008'
2022/12/16 11:55:55 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:56:05 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:56:09 rootcheck: INFO: Ending rootcheck scan.
2022/12/16 11:56:16 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:56:26 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:56:36 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:56:46 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:56:56 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:57:06 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:57:16 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:57:25 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
2022/12/16 11:57:35 wazuh-db: ERROR: There was an error assigning the groups to agent '008'
```

</details>



</details>

**Comment by Rebits** [comment] 2022-12-16 14:24
## Unexpected multiple `Agent 'id' doesn't comply with the registration time to be removed 


Unexpected `Agent 'id' doesn't comply with the registration time to be removed` warnings appears also in 4.4.
These warnings only appears using the default force configuration:
```
    <force>
      <enabled>yes</enabled>
    </force>
```


<details>

<summary> Multi Node - Remove agent and reconnect it - Development :yellow_circle: </summary>

- Configure the force option as default
- Configure external database integration
- Configure a manager cluster
- Insert the agent in the data base
```
+------+----------+------+------------------------------------------------------------------+
| id   | name     | ip   | agent_key                                                        |
+------+----------+------+------------------------------------------------------------------+
| 008  | testing3 | any  | 166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426 |
+------+----------+------+------------------------------------------------------------------+
```
- Start the agent (registered to the worker node)
- Check that unexpected warnings appears:
```
2022/12/16 13:53:56 wazuh-authd: WARNING: Duplicate ID, rejecting enrollment. Agent '009' doesn't comply with the registration time to be removed.
```



</details>


<details>

<summary> Multi Node - Remove agent and reconnect it - Development  :yellow_circle: </summary>


- Configure the force option as the default
- Configure external database integration
- Configure a manager cluster
- Insert the agent in the database
```
+------+----------+------+------------------------------------------------------------------+
| id   | name     | ip   | agent_key                                                        |
+------+----------+------+------------------------------------------------------------------+
| 008  | testing3 | any  | 166bd2d3e9d4d03b46f43fe1c72c1e5ae9a2e5ad99797542adeefd39670eb426 |
+------+----------+------+------------------------------------------------------------------+
```
- Start the agent (registered to the worker node)
- Check that unexpected warning appears:
```
2022/12/16 14:06:02 wazuh-remoted: WARNING: (1408): Invalid ID 010 for the source ip: '172.31.7.103' (name 'unknown').
2022/12/16 14:06:07 wazuh-remoted: WARNING: (1408): Invalid ID 010 for the source ip: '172.31.7.103' (name 'unknown').
2022/12/16 14:06:07 wazuh-authd: WARNING: 9012: Duplicate ID
2022/12/16 14:06:12 wazuh-remoted: WARNING: (1408): Invalid ID 010 for the source ip: '172.31.7.103' (name 'unknown').
2022/12/16 14:06:12 wazuh-authd: WARNING: 9012: Duplicate ID
2022/12/16 14:06:15 rootcheck: INFO: Ending rootcheck scan.
2022/12/16 14:06:16 wazuh-remoted: INFO: (1409): Authentication file changed. Updating.
2022/12/16 14:06:16 wazuh-remoted: INFO: (1410): Reading authentication keys file.
```

</details>

**Comment by Rebits** [comment] 2022-12-16 15:37
- Regarding `wazuh-db` errors, were already reported in https://github.com/wazuh/wazuh/issues/15665
- Regarding `wazuh-analysisd` errors, were already reported in https://github.com/wazuh/wazuh/issues/15260

**Comment by jmv74211** [comment] 2022-12-19 08:53
## Closing conclusion 👍🏼  

|||
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 

The tested development has been approved since the reported issues have not been introduced in this development but also occur in production. These are as follows:

**(1): Unexpected wazuh-db and wazuh-analysisd errors during the corrupt key case when the force option is configured to replace agents even for active ones.** 🔵 

We have added the following [comment](https://github.com/wazuh/wazuh/issues/15665#issuecomment-1355101494) in this already reported [issue](Cluster error while sending agent-groups data to wazuh-db) to give more details about that.

**(2): Unexpected multiple Agent 'id' doesn't comply with the registration time to be removed when an agent is registered** 🔵 

Unexpected duplicate ID warnings were detected when no previous agent was registered. The following issue has been opened to report this case [wazuh#15701](https://github.com/wazuh/wazuh/issues/15701).

**Closed** 2022-12-19 09:36 UTC
Labels: team/qa, target/4.4.0, type/dev-testing, subteam/qa-main
