### ISSUE TITLE
Full Yellow Local - Fix Agentd tests in 4.2

### ISSUE THREAD

**Issue by juliamagan** [wazuh/wazuh-qa#1521] opened 2021-06-29 12:33 UTC
## Description

This issue is part of the [full-green epic issue](https://github.com/wazuh/wazuh-qa/issues/1516). After the research #1493, we could see that `agentd` tests aren't working properly. In order to sanitize current tests is necessary to fix `agentd` tests. 

### Pipeline parameters

|  Jenkins branch  | QA branch   | 
|- |- |
|  4.2 |   1516-4.2.0-full-green |

### Packages details

Type | Format | Architecture | Version | Revision | Tag | File name
-- | -- | -- | -- | -- | -- | --
Server | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-manager-4.2.0-1.1493.x86_64.rpm
Agent | rpm | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.x86_64.rpm
Agent | Windows | x86_64 | 4.2.0 | 40207 | v4.2.0-rc8 | wazuh-agent-4.2.0-1.1493.msi

#### Agent
```
agent.debug=2
execd.debug=2
monitord.rotate_log=0
```

### Test Execution - Results

|   |  **Local** | **Jenkins**  |  **Status** 
|:--:|:--: |:--:|:--:|
|**Test Execution 1**|  [Linux Agent](https://github.com/wazuh/wazuh-qa/files/6746941/test_agentd_r1.log), [Windows Agent](https://github.com/wazuh/wazuh-qa/files/6743341/Results_Test_Agentd_Cycle1x2.log)   |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/868/)   |  🔴
|**Test Execution 2**|  [Linux Agent](https://github.com/wazuh/wazuh-qa/files/6746944/test_agentd_r2.log), [Windows Agent](https://github.com/wazuh/wazuh-qa/files/6743346/Results_Test_Agentd_Cycle2x2.log)   |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/909/)   |  🔴
|**Test Execution 3**|  [Linux Agent](https://github.com/wazuh/wazuh-qa/files/6746947/test_agentd_r3.log), [Windows Agent](https://github.com/wazuh/wazuh-qa/files/6743356/Results_Test_Agentd_Cycle3.log)   |   [Build](https://devel.ci.wazuh.info/view/Tests/job/Test_integration/942/)  |  🔴

        
## Development

In Linux agent the test case 14 of `test_agent_agentd_enrollment` due to an SSL error, the connection is refused by the manager. We need to check why this is happening and solve it.
In Windows agent, it seems that `control_service` isn't starting the service as expected in `test_agentd_state_config` for custom values in state interval.
This fix should be developed in a branch from 4.2, and it must be merged in the epic issue full-green branch `1516-4.2.0-full-green`.

In order to finish this issue the following tasks should be fulfilled:

**Linux**:
  - [x] `test_agentd/test_agent_auth_enrollment.py`:
      > `test_agent_auth_enrollment.py::test_agent_auth_enrollment[get_configuration0-test_case14]`    
  - [x] `test_agend/test_agentd_enrollment_params.py`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case14]`  

The tests from above are failing due to a problem with the library of OpenSSL, since the manager is forced to use TLSv1_2 instead of TLSv1_1. We want to solve this problem by deprecating the use of `authd_sim.py`. We have created issue #1585. We have decided to delete this test case and we will include it again when refactoring and issue #1585 are done. We have been working on this fix in branch `1521-2-delete-tls1-agentd`. **PR**: https://github.com/wazuh/wazuh-qa/pull/1629                    
  - [x] `test_agentd/test_agentd_reconnection.py`: **False positive**
      > `test_agentd_reconnection.py::test_agentd_reconection_enrollment_with_keys[tcp]`
      > `test_agentd_reconnection.py::test_agentd_reconection_enrollment_no_keys_file[tcp]`
      > `test_agentd_reconnection.py::test_agentd_reconection_enrollment_no_keys[tcp]`
      > `test_agentd_reconnection.py::test_agentd_initial_enrollment_retries[tcp]`
      > `test_agentd_reconnection.py::test_agentd_connection_retries_pre_enrollment[tcp]`
      > `test_agentd_reconnection.py::test_agentd_reconection_enrollment_with_keys[udp]`
      > `test_agentd_reconnection.py::test_agentd_reconection_enrollment_no_keys_file[udp]`
      > `test_agentd_reconnection.py::test_agentd_reconection_enrollment_no_keys[udp]`
      > `test_agentd_reconnection.py::test_agentd_initial_enrollment_retries[udp]`
      > `test_agentd_reconnection.py::test_agentd_connection_retries_pre_enrollment[udp]`

  We have launched these tests three times in Jenkins and more than three times in two different local environments and the tests passed.

**Windows**:
  - [x] `test_agentd/test_agentd_reconnection.py`:
      > `test_agentd_reconnection.py::test_agentd_connection_retries_pre_enrollment[tcp]` 

When executed only the failed case, the test passed. Tried to launch with different tests before it and it fails randomly.

  - [x] `test_agentd/test_agentd_enrollment_params.py`: _Pending (just failed once)_
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case1]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case2]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case8]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case10]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case11]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case15]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case17]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case21]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case27]`
      > `test_agentd_enrollment_params.py::test_agent_agentd_enrollment[get_configuration0-test_case28]`

When executed only `test_agentd/test_agentd_enrollment_params.py`, all tests passed, included the test of TLSv1_1.

  - [x] https://github.com/wazuh/wazuh-qa/issues/1588

- [x] Full yellow in `agentd` tests for every supported OS
- [x] Documentation of any important change done for these tests or the used tools
- [ ] Merge with `1516-4.2.0-full-green`

**Comment by snaow** [comment] 2021-07-21 14:14
After working on the first phases of tests, we realize that they are working but they fail randomly, probably related to the Windows service inconsistency wazuh@wazuh#9298.

@Molter73 will take over this issue to keep testing.

**Comment by Molter73** [comment] 2021-07-22 06:39
I've run the tests multiple times on a Windows agent with 2 cores, 2 GB of RAM, disabling the syscheck, rootcheck, SCA and syscollector modules. When using this configuration, the only tests that failed are the ones on `test_agentd\test_agentd_state_config.py` that are being addressed in #1588.

I believe the errors are related to wazuh/wazuh#9298 as @snaow mentioned and are being caused by a heavy load on the disk that ultimately causes the agent to stall when stopping/starting. A similar conclusion was drawn when investigating #1593.

If anyone else on the team can confirm that disabling verbose modules that are unused in these tests, it would be great.

Here are the reports from the tests I ran:
- [R0.zip](https://github.com/wazuh/wazuh-qa/files/6860347/agentd-full-0.zip)
- [R1.zip](https://github.com/wazuh/wazuh-qa/files/6860348/agentd-full-1.zip)
- [R2.zip](https://github.com/wazuh/wazuh-qa/files/6860349/agentd-full-2.zip)
- [R3.zip](https://github.com/wazuh/wazuh-qa/files/6860350/agentd-full-3.zip)

**Comment by juliamagan** [comment] 2021-07-23 16:12
I'll be launching three rounds of `test_agentd` in Windows to check if disabling `rootcheck`, `sca`, `syscheck `and `syscollector `everything works properly.

**Comment by juliamagan** [comment] 2021-07-26 13:44
I'll be launching three rounds of test_agentd in Ubuntu to check if everything works properly.

**Comment by snaow** [comment] 2021-08-10 16:48
Branch dev: `1521-full-green-agentd-fix`

**Comment by snaow** [comment] 2021-08-10 18:59
Closed by: https://github.com/wazuh/wazuh-qa/pull/1702

**Closed by snaow** 2021-08-10 18:59 UTC
Labels: status/blocked-ext, team/qa, feature/agentd, type/fix
