### ISSUE TITLE
The checksums of the 4.9.0 packages do not match the expected ones

### ISSUE THREAD

**Issue by MARCOSD4** [wazuh/wazuh-qa#5729] opened 2024-09-06 08:08 UTC
## Description

After the release of 4.9.0, it was found that the checksums of some packages do not match those that should have been expected. That is, the packages have an expected checksum, which can be checked in the [documentation](https://documentation.wazuh.com/current/installation-guide/packages-list.html) itself, but when downloading the package and manually checking the checksum, it is completely different.

This has been tested for deb files:

**Wazuh Manager:**

```console
$ Expected sha512 checksum: 
bf990d95b6ce6cc16297df819ea3b7697aaab81d725b8efd012cd43d8a312a239433ae605d65e15a300089468f034a835036fa1668899e6bbd6b0b7be1b71230

$ sha512sum wazuh-manager_4.9.0-1_amd64.deb
f21d68ae352f23db47a274ae6f35aa617313057397282a2742674ef1eab189f7e5865acdef55661e4a0b19e94d76e320a34da2a82abdfd23c00f3fea64992549
```

**Wazuh Indexer:**

```console
$ Expected sha512 checksum: 
a555142141ed14a42769cde03eb475daec8ca470f6f8911154e342d6d1866ed591d46a9b0d450cd09ab9f1be441550220359242e3cc03f637f7a3053415b91eb

$ sha512sum wazuh-indexer_4.9.0-1_amd64.deb
a250ce2a92a7a34dc98c2fcbe0b246c1e41464053c98d67766e97079bbda5ca1e6ad9e742b10819cbac27974b52345fdddf135eca56bdff1b24c325b9b207da6
```

**Wazuh Dashboard:**

```console
$ Expected sha512 checksum: 
b2712654730dd0f589836cec7af507054b2379afaaf06b1a94b5bda864e7623315efa9001cc741abbddf018aef6543bb39f9f470feaf9d658e3b3f8b3b6fb479

$ sha512sum wazuh-dashboard_4.9.0-1_amd64.deb
44eacb01b1a767116326f02abd20dac6a65b9f41966e2380da9a19bcb5aee6210778696ec5cbf84f5729e73a99976831ad3bfbab2f518700b9060e92961fbd9a
```

**Wazuh Agent:**

```console
$ Expected sha512 checksum: 
c91e2f1f92e0f075a73c310aeb95e10ed5b58f5e73797d35462d60af65d887d61d9273344f951476845ac52a2b260bee7598eab00dbcd21be780d6446f371fc5

$ sha512sum wazuh-agent_4.9.0-1_amd64.deb
1fc3fca5c9da14bb4694e4b6713a3e40a04dfe56ed81fc656baab2c02aba16a6a23eaca7de2fa3b5acd7cca2722672c144cb7a8cd251901b73b782d835dd6cec
```

It should be checked if it also happens for other files (rpm, pkg, msi, etc.). This is probably related to the modification that the package experiences when it is signed.

Further research is required.

**Comment by juliamagan** [comment] 2024-09-06 11:40
It seems that at the time of [signing packages](https://github.com/wazuh/wazuh-jenkins/issues/6910#issuecomment-2322371661), the template was not correctly parameterized, checksum was not added and set to true. The logs show that it is set to false:

```
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: Target list:
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'manager-rpm-x86_64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'manager-deb-amd64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-rpm-i386', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-rpm-x86_64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-rpm-armv7hl', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-rpm-aarch64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-deb-i386', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-deb-amd64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-deb-armhf', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-deb-arm64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-rpm5-i386', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-rpm5-x86_64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-windows-i386', 'sign': False, 'verify': True, 'upload': False, 'tag': False, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-macos-intel64', 'sign': False, 'notarize': True, 'verify': True, 'verify_notarize': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'agent-macos-arm64', 'sign': False, 'notarize': True, 'verify': True, 'verify_notarize': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'dashboard-deb-amd64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'dashboard-rpm-x86_64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'indexer-deb-amd64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
[2024-08-30 17:24:06] [INFO] [S3-SIGN-CHECK]: - {'target': 'indexer-rpm-x86_64', 'sign': True, 'verify': True, 'upload': True, 'tag': True, 'checksum': False}
```

**Comment by jnasselle** [comment] 2024-09-06 11:59
# Update

- This already contemplates the checksum change after signing https://github.com/wazuh/wazuh-jenkins/pull/6637
- Several files suffer the same condition
```
wazuh-manager_4.9.0-1_amd64.deb  checksum mismatch
wazuh-dashboard_4.9.0-1_amd64.deb  checksum mismatch
wazuh-indexer_4.9.0-1_amd64.deb  checksum mismatch
wazuh-agent_4.9.0-1_amd64.deb  checksum mismatch
wazuh-agent_4.9.0-1_i386.deb  checksum mismatch
wazuh-agent_4.9.0-1_arm64.deb  checksum mismatch
wazuh-agent_4.9.0-1_armhf.deb  checksum mismatch
wazuh-manager-4.9.0-1.x86_64.rpm  checksum mismatch
wazuh-dashboard-4.9.0-1.x86_64.rpm  checksum mismatch
wazuh-indexer-4.9.0-1.x86_64.rpm  checksum mismatch
wazuh-agent-4.9.0-1.x86_64.rpm  checksum mismatch
wazuh-agent-4.9.0-1.i386.rpm  checksum mismatch
wazuh-agent-4.9.0-1.aarch64.rpm  checksum mismatch
wazuh-agent-4.9.0-1.armv7hl.rpm  checksum mismatch
wazuh-agent-4.9.0-1.el5.i386.rpm  checksum mismatch
wazuh-agent-4.9.0-1.el5.x86_64.rpm  checksum mismatch
wazuh-agent-4.9.0-1.msi  checksum mismatch
wazuh-agent-4.9.0-1.intel64.pkg  checksum mismatch
wazuh-agent-4.9.0-1.arm64.pkg  checksum mismatch
wazuh_agent_v4.9.0_linux_amd64.deb.wpk  checksum mismatch
wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk  checksum mismatch
wazuh_agent_v4.9.0_macos_intel64.pkg.wpk  checksum mismatch
wazuh_agent_v4.9.0_windows.wpk  checksum mismatch
```
- @juliamagan points that this was caused by a wrong parameterization during the signing procedure https://github.com/wazuh/wazuh-jenkins/issues/6910

Setting this issue to "On hold" until a new procedure release with the right parametrization is launched in order to close it.

**Comment by rauldpm** [comment] 2024-09-06 12:24
We will not release the 4.9.0 packages again until the https://github.com/wazuh/wazuh/issues/25605 issue is fixed, we should prepare a script to download those packages locally, generate the correct checksum, and upload them to the checksum directory, if not, we will have to wait until the 4.9.1 release, and we need to fix this asap for security reasons

This should be done to pre-release and production (when the 4.9.0 packages are restored)

**Comment by SirStephanikus** [comment] 2024-09-06 13:05
I make a proposal, guys ... instead of releasing a buggy mess, simply ask your partners for a pre-release test.

I can not stress it enough ... each time you release a non-minor version, something breaks, GitHub and Reddit gets flooded with complaints. This is bad marketing!

I had even missing metainfo in Rocky-8 and now the 4.9.0 package is not available at all.

**Comment by jnasselle** [comment] 2024-09-06 14:08
# Update

- Allow pre-release
- Fixing checksums
- Invalidate CloudFront cache
- Validation
```
Downloading wazuh-manager_4.9.0-1_amd64.deb from https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-manager/wazuh-manager_4.9.0-1_amd64.deb
Downloading wazuh-manager_4.9.0-1_amd64.deb.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-manager_4.9.0-1_amd64.deb.sha512
wazuh-manager_4.9.0-1_amd64.deb: Checksum is valid.
Downloading wazuh-dashboard_4.9.0-1_amd64.deb from https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-dashboard/wazuh-dashboard_4.9.0-1_amd64.deb
Downloading wazuh-dashboard_4.9.0-1_amd64.deb.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-dashboard_4.9.0-1_amd64.deb.sha512
wazuh-dashboard_4.9.0-1_amd64.deb: Checksum is valid.
Downloading wazuh-indexer_4.9.0-1_amd64.deb from https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-indexer/wazuh-indexer_4.9.0-1_amd64.deb
Downloading wazuh-indexer_4.9.0-1_amd64.deb.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-indexer_4.9.0-1_amd64.deb.sha512
wazuh-indexer_4.9.0-1_amd64.deb: Checksum is valid.
Downloading wazuh-agent_4.9.0-1_amd64.deb from https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_amd64.deb
Downloading wazuh-agent_4.9.0-1_amd64.deb.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_amd64.deb.sha512
wazuh-agent_4.9.0-1_amd64.deb: Checksum is valid.
Downloading wazuh-agent_4.9.0-1_i386.deb from https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_i386.deb
Downloading wazuh-agent_4.9.0-1_i386.deb.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_i386.deb.sha512
wazuh-agent_4.9.0-1_i386.deb: Checksum is valid.
Downloading wazuh-agent_4.9.0-1_arm64.deb from https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_arm64.deb
Downloading wazuh-agent_4.9.0-1_arm64.deb.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_arm64.deb.sha512
wazuh-agent_4.9.0-1_arm64.deb: Checksum is valid.
Downloading wazuh-agent_4.9.0-1_armhf.deb from https://packages-dev.wazuh.com/pre-release/apt/pool/main/w/wazuh-agent/wazuh-agent_4.9.0-1_armhf.deb
Downloading wazuh-agent_4.9.0-1_armhf.deb.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_4.9.0-1_armhf.deb.sha512
wazuh-agent_4.9.0-1_armhf.deb: Checksum is valid.
Downloading wazuh-manager-4.9.0-1.x86_64.rpm from https://packages-dev.wazuh.com/pre-release/yum/wazuh-manager-4.9.0-1.x86_64.rpm
Downloading wazuh-manager-4.9.0-1.x86_64.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-manager-4.9.0-1.x86_64.rpm.sha512
wazuh-manager-4.9.0-1.x86_64.rpm: Checksum is valid.
Downloading wazuh-dashboard-4.9.0-1.x86_64.rpm from https://packages-dev.wazuh.com/pre-release/yum/wazuh-dashboard-4.9.0-1.x86_64.rpm
Downloading wazuh-dashboard-4.9.0-1.x86_64.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-dashboard-4.9.0-1.x86_64.rpm.sha512
wazuh-dashboard-4.9.0-1.x86_64.rpm: Checksum is valid.
Downloading wazuh-indexer-4.9.0-1.x86_64.rpm from https://packages-dev.wazuh.com/pre-release/yum/wazuh-indexer-4.9.0-1.x86_64.rpm
Downloading wazuh-indexer-4.9.0-1.x86_64.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-indexer-4.9.0-1.x86_64.rpm.sha512
wazuh-indexer-4.9.0-1.x86_64.rpm: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.x86_64.rpm from https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.9.0-1.x86_64.rpm
Downloading wazuh-agent-4.9.0-1.x86_64.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.x86_64.rpm.sha512
wazuh-agent-4.9.0-1.x86_64.rpm: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.i386.rpm from https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.9.0-1.i386.rpm
Downloading wazuh-agent-4.9.0-1.i386.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.i386.rpm.sha512
wazuh-agent-4.9.0-1.i386.rpm: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.aarch64.rpm from https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.9.0-1.aarch64.rpm
Downloading wazuh-agent-4.9.0-1.aarch64.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.aarch64.rpm.sha512
wazuh-agent-4.9.0-1.aarch64.rpm: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.armv7hl.rpm from https://packages-dev.wazuh.com/pre-release/yum/wazuh-agent-4.9.0-1.armv7hl.rpm
Downloading wazuh-agent-4.9.0-1.armv7hl.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.armv7hl.rpm.sha512
wazuh-agent-4.9.0-1.armv7hl.rpm: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.el5.i386.rpm from https://packages-dev.wazuh.com/pre-release/yum5/i386/wazuh-agent-4.9.0-1.el5.i386.rpm
Downloading wazuh-agent-4.9.0-1.el5.i386.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.el5.i386.rpm.sha512
wazuh-agent-4.9.0-1.el5.i386.rpm: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.el5.x86_64.rpm from https://packages-dev.wazuh.com/pre-release/yum5/x86_64/wazuh-agent-4.9.0-1.el5.x86_64.rpm
Downloading wazuh-agent-4.9.0-1.el5.x86_64.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.el5.x86_64.rpm.sha512
wazuh-agent-4.9.0-1.el5.x86_64.rpm: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.msi from https://packages-dev.wazuh.com/pre-release/windows/wazuh-agent-4.9.0-1.msi
Downloading wazuh-agent-4.9.0-1.msi.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.msi.sha512
wazuh-agent-4.9.0-1.msi: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.intel64.pkg from https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.9.0-1.intel64.pkg
Downloading wazuh-agent-4.9.0-1.intel64.pkg.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.intel64.pkg.sha512
wazuh-agent-4.9.0-1.intel64.pkg: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.arm64.pkg from https://packages-dev.wazuh.com/pre-release/macos/wazuh-agent-4.9.0-1.arm64.pkg
Downloading wazuh-agent-4.9.0-1.arm64.pkg.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.arm64.pkg.sha512
wazuh-agent-4.9.0-1.arm64.pkg: Checksum is valid.
Downloading wazuh_agent_v4.9.0_linux_amd64.deb.wpk from https://packages-dev.wazuh.com/pre-release/wpk/linux/deb/amd64/wazuh_agent_v4.9.0_linux_amd64.deb.wpk
Downloading wazuh_agent_v4.9.0_linux_amd64.deb.wpk.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_linux_amd64.deb.wpk.sha512
wazuh_agent_v4.9.0_linux_amd64.deb.wpk: Checksum is valid.
Downloading wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk from https://packages-dev.wazuh.com/pre-release/wpk/linux/rpm/x86_64/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk
Downloading wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk.sha512
wazuh_agent_v4.9.0_linux_x86_64.rpm.wpk: Checksum is valid.
Downloading wazuh_agent_v4.9.0_macos_intel64.pkg.wpk from https://packages-dev.wazuh.com/pre-release/wpk/macos/pkg/intel64/wazuh_agent_v4.9.0_macos_intel64.pkg.wpk
Downloading wazuh_agent_v4.9.0_macos_intel64.pkg.wpk.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_macos_intel64.pkg.wpk.sha512
wazuh_agent_v4.9.0_macos_intel64.pkg.wpk: Checksum is valid.
Downloading wazuh_agent_v4.9.0_windows.wpk from https://packages-dev.wazuh.com/pre-release/wpk/windows/wazuh_agent_v4.9.0_windows.wpk
Downloading wazuh_agent_v4.9.0_windows.wpk.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh_agent_v4.9.0_windows.wpk.sha512
wazuh_agent_v4.9.0_windows.wpk: Checksum is valid.
Downloading wazuh-agent_v4.9.0-sol10-i386.pkg from https://packages-dev.wazuh.com/pre-release/solaris/i386/10/wazuh-agent_v4.9.0-sol10-i386.pkg
Downloading wazuh-agent_v4.9.0-sol10-i386.pkg.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol10-i386.pkg.sha512
wazuh-agent_v4.9.0-sol10-i386.pkg: Checksum is valid.
Downloading wazuh-agent_v4.9.0-sol10-sparc.pkg from https://packages-dev.wazuh.com/pre-release/solaris/sparc/10/wazuh-agent_v4.9.0-sol10-sparc.pkg
Downloading wazuh-agent_v4.9.0-sol10-sparc.pkg.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol10-sparc.pkg.sha512
wazuh-agent_v4.9.0-sol10-sparc.pkg: Checksum is valid.
Downloading wazuh-agent_v4.9.0-sol11-i386.p5p from https://packages-dev.wazuh.com/pre-release/solaris/i386/11/wazuh-agent_v4.9.0-sol11-i386.p5p
Downloading wazuh-agent_v4.9.0-sol11-i386.p5p.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol11-i386.p5p.sha512
wazuh-agent_v4.9.0-sol11-i386.p5p: Checksum is valid.
Downloading wazuh-agent_v4.9.0-sol11-sparc.p5p from https://packages-dev.wazuh.com/pre-release/solaris/sparc/11/wazuh-agent_v4.9.0-sol11-sparc.p5p
Downloading wazuh-agent_v4.9.0-sol11-sparc.p5p.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent_v4.9.0-sol11-sparc.p5p.sha512
wazuh-agent_v4.9.0-sol11-sparc.p5p: Checksum is valid.
Downloading wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz from https://packages-dev.wazuh.com/pre-release/hp-ux/wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz
Downloading wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz.sha512
wazuh-agent-4.9.0-1-hpux-11v3-ia64.tar.gz: Checksum is valid.
Downloading wazuh-agent-4.9.0-1.aix.ppc.rpm from https://packages-dev.wazuh.com/pre-release/aix/wazuh-agent-4.9.0-1.aix.ppc.rpm
Downloading wazuh-agent-4.9.0-1.aix.ppc.rpm.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-agent-4.9.0-1.aix.ppc.rpm.sha512
wazuh-agent-4.9.0-1.aix.ppc.rpm: Checksum is valid.
Downloading wazuh-4.9.0.ova from https://packages-dev.wazuh.com/pre-release/vm/wazuh-4.9.0.ova
Downloading wazuh-4.9.0.ova.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-4.9.0.ova.sha512
wazuh-4.9.0.ova: Checksum is valid.
Downloading wazuh-wazuh-4.9.0.tar.gz from https://packages-dev.wazuh.com/pre-release/puppet-module/wazuh-wazuh-4.9.0.tar.gz
Downloading wazuh-wazuh-4.9.0.tar.gz.sha512 from https://packages-dev.wazuh.com/pre-release/checksums/wazuh/4.9.0/wazuh-wazuh-4.9.0.tar.gz.sha512
wazuh-wazuh-4.9.0.tar.gz: Checksum is valid.
```

**Comment by jnasselle** [comment] 2024-09-09 09:54
# Update

ETA changed to Sept10

**Closed as completed** 2024-09-10 09:27 UTC
Labels: level/task, type/bug
