### ISSUE TITLE
Fix `test_files/test_max_files_per_second/test_max_files_per_second.py`

### ISSUE THREAD

**Issue by Molter73** [wazuh/wazuh-qa#1655] opened 2021-07-27 09:38 UTC
|Related Issue|
|--|
|#1516 #1539|

```
Module: File Integrity Monitoring
Target: Manager and Agent   
OS: Linux
```

|  Type | Description  |
|--|--|
|Test Path | test_files/test_max_files_per_second/test_max_files_per_second.py
| Consistent | No
| Test Execution | 1/3 executions failed
| Cases Failed | [get_configuration0-True]
| Summary | `test_max_files_per_second.py` might take longer than expected when the inode collision mechanism kicks in.
| Error message |  TimeoutError: End of scheduled scan not detected after 10.0 seconds

In order to finish this issue the following tasks should be fulfilled:
- [x] Fails research.
- [x] Fix the test: Add timeout
- [x] Full Green/Yellow in `test_files/test_max_files_per_second/test_max_files_per_second.py`. 
- [x] Documentation of any important change done for these tests or the used tools.

**Comment by juliamagan** [comment] 2021-07-28 16:08
## Update 07/28

It is really difficult to reproduce the error. This error is due to Wazuh takes a few seconds more than the timeout to generate the log. We have increased the timeout and it worked in ten rounds in a CentOS 8 manager. It remains to test it in a CentOS 8 agent.

**Comment by snaow** [comment] 2021-08-24 19:44
Closed by https://github.com/wazuh/wazuh-qa/pull/1667

**Closed by snaow** 2021-08-24 19:44 UTC
Labels: team/qa, feature/fim, type/fix
