### ISSUE TITLE
Internal change in Windows Agent installer

### ISSUE THREAD

**Issue by verdx** [wazuh/wazuh-qa#3625] opened 2022-11-21 12:45 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
| 4.4 | https://github.com/wazuh/wazuh/issues/15414| https://github.com/wazuh/wazuh/pull/15447 |

## Description

The changes made should stop the Windows Agent MSI installer from opening a `CMD` popup window in the middle of the installation for some milliseconds. The way of calling a Custom Action to kill the GUI window has changed, but its functioning should be the same.

## Proposed checks

For every Windows supported:
- [x] Agent installation
- [x] Agent upgrade from version 4.2.x and 4.3.x with open GUI
- [x] Agent upgrade from version 4.2.x and 4.3.x without an open GUI

## Expected results

The upgrade must finish without errors and the installation can't force a reboot no matter what options are chosen in the FilesInUse Dialog. No black popup window should open during the installation

**Comment by fedepacher** [comment] 2022-11-22 19:18
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @fedepacher |     |

### Testing environment

| OS | OS version | Deployment                                     | Notes |
|----|------------|-----------------------------------------------|-----------|
|  Windows  | XP | Vagrant box |

### Tested packages

| `wazuh-manager` | `wazuh-agent` |
|-----------------|---------------|
| [deb](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-3625.windows.installer.todelete_amd64.deb) |[msi](https://packages-dev.wazuh.com/warehouse/test/4.4/windows/wazuh-agent-4.4.0-3625.windows.installer.todelete.msi)|

### Status

- [x] In progress
- [ ] Pending Review
- [ ] Team leader approved (@Rebits )
- [ ] QA team manager approved (@jmv74211)
- [ ] DEV team leader approved (@alberpilot )


### Conclusion :green_circle:

At this point, the ugrade seems to work properly but in Windows XP I could not reach a black popup window after upgrading from 4.2.7 to 4.3.10.

**Comment by fedepacher** [comment] 2022-11-22 19:24
# Testing results :green_circle:


<details>
<summary>Windows XP</summary>

### Unfixed

<details><summary>Install unfixed package</summary>

  1. Install `wazuh-agent v4.2.7` package
  2. Upgrade to `wazuh-agent v4.3.10`
  3. No black popup window was opened during the installation
  4. A FilesInUse Dialog appears with the following message:
     ```
     You must restart your system for the configuration changes made to Wazuh Agent to take effect. Click Yes to restart now or No if you plan to manually restart later.
     ```

</details>


### Upgrade

<details><summary>Upgrade from 4.2.7 to 4.4 with GUI opened:green_circle:</summary>

  1. Upgrade to `wazuh-agent v4.4.0` package
  2. A FilesInUse Dialog appears with the following message:
     ```
     Some files that need to be updated are currently in use
     The following applications are using files that need to be updated by this setup. Close these applications and click Retry to continue setup or Exit to exit it.
     ```
  3. Ignore FileInUse Dialog.
  4. The Wazuh Agent application was closed.
  5. No black popup window was opened during the installation.
  6. Agent was relaunched successfully after finishing installation when the `Run Agent configuration interface` checkbox was checked.
  7. No ERROR or WARNING messages were found in the `ossec.log` file.

</details>


<details><summary>Upgrade from 4.2.7 to 4.4 with GUI closed:green_circle:</summary>

  1. Upgrade to `wazuh-agent v4.4.0` package
  2. No black popup window was opened during the installation
  3. Agent was relaunched successfully after finishing installation when the `Run Agent configuration interface` checkbox was checked.
  4. No ERROR or WARNING messages were found in the `ossec.log` file.

</details>


<details><summary>Upgrade from 4.3.10 to 4.4 with GUI opened:green_circle:</summary>

  1. Upgrade to `wazuh-agent v4.4.0` package
  2. A FilesInUse Dialog appears with the following message:
     ```
     Some files that need to be updated are currently in use
     The following applications are using files that need to be updated by this setup. Close these applications and click Retry to continue setup or Exit to exit it.
     ```
  3. Ignore FileInUse Dialog.
  4. The Wazuh Agent application was closed.
  5. No black popup window was opened during the installation.
  6. Agent was relaunched successfully after finishing installation when the `Run Agent configuration interface` checkbox was checked.
  7. No ERROR or WARNING messages were found in the `ossec.log` file.

</details>

<details><summary>Upgrade from 4.3.10 to 4.4 with GUI closed:green_circle:</summary>

  1. Upgrade to `wazuh-agent v4.4.0` package
  2. No black popup window was opened during the installation
  3. Agent was relaunched successfully after finishing installation when the `Run Agent configuration interface` checkbox was checked.
  4. No ERROR or WARNING messages were found in the `ossec.log` file.

</details>

</details>

**Comment by Rebits** [comment] 2022-11-23 18:53
### Update - 23/11/2022

- Perform proposed checks for W10, W11, WS2012, WS2016, WS2019 and WS2020

**Comment by Rebits** [comment] 2022-11-24 15:48
### Update - 24/11/2022
- Perform proposed checks for Windows Vista, Windows 8, Windows Server 2003 and Windows Server 2008

**Comment by jmv74211** [comment] 2022-11-28 16:49
About (2) in https://github.com/wazuh/wazuh-qa/issues/3625#issuecomment-1329317087, @Rebits will test the case in `4.3.0` to find out whether this is caused by the new development or has been going on for a long time

If it is new it will be considered as a stopper, otherwise an issue will be opened and reported for the future.

**Comment by Rebits** [comment] 2022-11-28 17:59
About (2) https://github.com/wazuh/wazuh-qa/issues/3625#issuecomment-1329317087, the `Files in Use` menu was introduced in `4.4.0`, so this error is not reproducible for the `4.3.0` version.

In addition, it seems that for some systems, like Windows 7, `Retry` does not detect correctly when the GUI is closed.

[w7retry.webm](https://user-images.githubusercontent.com/11089305/204347955-54a4aadb-9329-48b4-bbc2-25914248ee68.webm)

**Comment by verdx** [comment] 2022-12-02 11:27
This seems to happen because when retry is clicked, somehow the MSI action to close the GUI is called, but there isn't direct control on that menu or when does Windows execute the Custom Action. I have tried changing the time when it is called to `BEFORE=InstallFinalize` but that way the error this PR removes comes again:

![error2349](https://user-images.githubusercontent.com/61122643/205282759-446f527f-690d-46f6-909b-ba1b0f0923e3.png)

**Comment by jmv74211** [comment] 2022-12-02 15:46
## Closing conclusion 👍🏼

|| |
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 
| ⚫ |Discarded |

Everything seems to work properly. The development has been approved taking into account the following considerations:


**(1) During Windows event manual testing, it has been detected that the Run agent configuration Interface option does not work correctly in Windows agent installation.** 🔵

This was already reported in [wazuh#12906](https://github.com/wazuh/wazuh/issues/12906). It will be investigated and fixed in future versions.

**(2) Files in use menu is inconsistent along the Windows OS in the `v4.2` agent upgrade. This menu appears with the GUI opened only in some of the proposed OS. The rest of the OS proceeds with the upgrade directly**. ⚫

This happens from 4.4, but it depends on the Windows 0S if it appears or not. This is marked as an "allowed consequence".

**Comment by alberpilot** [comment] 2022-12-12 15:35
Comment about issue: https://github.com/wazuh/wazuh/issues/15497

**Closed** 2022-12-12 16:14 UTC
Labels: team/qa, target/4.4.0, type/dev-testing, subteam/qa-main
