### ISSUE TITLE
System one_manager_agent false positive in 4.8.0-beta4

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5099] opened 2024-03-14 11:16 UTC
### Description

During [Release 4.8.0 - Beta 4 - System tests](https://github.com/wazuh/wazuh/issues/22481) it has been detected unexpected errors
in the one_manager_agent environment tests `test_fim/test_files/test_files_cud.py`:

We can discard product error due to the expected log appear in the manager logs:
```
2024/03/13 22:38:31 wazuh-db[73458] wdb_parser.c:261 at wdb_parse(): DEBUG: Agent 001 query: syscheck save2 {"attributes":{"checksum":"affb741262f76cb9651094126684d110caac9684","gid":"109","group_name":"wazuh","hash_md5":"fb4e1b0bd3ed16116f34533b9966e561","hash_sha1":"6dfbc82a745ed51fef88bd07edacc6e37519572c","hash_sha256":"5d1606c523d12b093ef0fca39f3bae32b597fd9ea73fe1c4fcc76d2a627d6bd6","inode":585721,"mtime":1710365910,"perm":"rw-------","size":8,"type":"file","uid":"107","user_name":"wazuh"},"path":"/testdir2/tmp__l02kja","timestamp":1710365911,"version":"2.0"}
```

It is necessary to research this bug in test_file_cud test.

### Evidences

- **Test case**: `test_file_cud[testdir2-modify`
- **Error**:
```
E                   TimeoutError: Did not found the expected callback in wazuh-manager: .*Agent 001 query: (.+) save2
```
- **Report**: [one_manager_agent.zip](https://github.com/wazuh/wazuh-qa/files/14601357/one_manager_agent.zip)

**Comment by juliamagan** [comment] 2024-03-15 13:44
As in other iterations, the log does appear. The problem is in the `HostMonitor`, which does not work as expected in virtualized environments. We can do an analysis and refactor of this method, or wait for the migration of the system tests.

In the meantime, it is proposed to mark the issue as `qa_known`, and when the system tests fail it, before opening an issue directly, check the environment logs.

**Comment by juliamagan** [comment] 2024-04-10 10:40
After the meeting with @davidjiglesias and @rauldpm, we are going to close this issue as not planned, and the system tests will be launched locally if necessary until we can migrate these tests to the new framework.

**Closed by juliamagan** 2024-04-10 10:40 UTC
Labels: level/task, type/bug, qa_known
