### ISSUE TITLE
Ubuntu Linux 22.04 SCA Policy - Update and rework - checks 2 to 2.2.16

### ISSUE THREAD

**Issue by 72nomada** [wazuh/wazuh-qa#3445] opened 2022-10-10 10:14 UTC
| Target version | Related issue | Related PR                                |
| -------------- | ------------- | ----------------------------------------- |
| 4.4.0          | #3390        | https://github.com/wazuh/wazuh/pull/15051 |

| Check ID | Check Name                                                               | Implemented | Ready for review | QA review |
| -------- | ------------------------------------------------------------------------ | ----------- | ---------------- | --------- |
| 2        | Services                                                                 |             |                  |           |
| 2.1      | Configure Time Synchronization                                           |             |                  |           |
| 2.1.1    | Ensure time synchronization is in use                                    |             |                  |           |
| 2.1.1.1  | Ensure a single time synchronization daemon is in use (Automated)        |             |                  |           |
| 2.1.2    | Configure chrony                                                         |             |                  |           |
| 2.1.2.1  | Ensure chrony is configured with authorized timeserver (Manual)          |             |                  |           |
| 2.1.2.2  | Ensure chrony is running as user _chrony (Automated)                     |             |                  |           |
| 2.1.2.3  | Ensure chrony is enabled and running (Automated)                         |             |                  |           |
| 2.1.3    | Configure systemd-timesyncd                                              |             |                  |           |
| 2.1.3.1  | Ensure systemd-timesyncd configured with authorized timeserver (Manual)  |             |                  |           |
| 2.1.3.2  | Ensure systemd-timesyncd is enabled and running (Automated)              |             |                  |           |
| 2.1.4    | Configure ntp                                                            |             |                  |           |
| 2.1.4.1  | Ensure ntp access control is configured (Automated)                      |             |                  |           |
| 2.1.4.2  | Ensure ntp is configured with authorized timeserver (Manual)             |             |                  |           |
| 2.1.4.3  | Ensure ntp is running as user ntp (Automated)                            |             |                  |           |
| 2.1.4.4  | Ensure ntp is enabled and running (Automated)                            |             |                  |           |
| 2.2      | Special Purpose Services                                                 |             |                  |           |
| 2.2.1    | Ensure X Window System is not installed (Automated)                      |             |                  |           |
| 2.2.2    | Ensure Avahi Server is not installed (Automated)                         |             |                  |           |
| 2.2.3    | Ensure CUPS is not installed (Automated)                                 |             |                  |           |
| 2.2.4    | Ensure DHCP Server is not installed (Automated)                          |             |                  |           |
| 2.2.5    | Ensure LDAP server is not installed (Automated)                          |             |                  |           |
| 2.2.6    | Ensure NFS is not installed (Automated)                                  |             |                  |           |
| 2.2.7    | Ensure DNS Server is not installed (Automated)                           |             |                  |           |
| 2.2.8    | Ensure FTP Server is not installed (Automated)                           |             |                  |           |
| 2.2.9    | Ensure HTTP server is not installed (Automated)                          |             |                  |           |
| 2.2.10   | Ensure IMAP and POP3 server are not installed (Automated)                |             |                  |           |
| 2.2.11   | Ensure Samba is not installed (Automated)                                |             |                  |           |
| 2.2.12   | Ensure HTTP Proxy Server is not installed (Automated)                    |             |                  |           |
| 2.2.13   | Ensure SNMP Server is not installed (Automated)                          |             |                  |           |
| 2.2.14   | Ensure NIS Server is not installed (Automated)                           |             |                  |           |
| 2.2.15   | Ensure mail transfer agent is configured for local-only mode (Automated) |             |                  |           |
| 2.2.16   | Ensure rsync service is either not installed or masked (Automated)       |             |                  |           |

**Comment by Rebits** [comment] 2022-11-02 17:28
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/15051/commits/4cac289aeb0f2daa7309cd8840793409e0f24019 | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Ubuntu | [Manager](https://packages-dev.wazuh.com/warehouse/test/4.4/deb/var/wazuh-manager_4.4.0-qa.vr.3443_amd64.deb)|



### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@72nomada )

**Comment by Rebits** [comment] 2022-11-02 18:36
## Testing results :large_blue_circle:


<details>

<summary> 2.1.2.2 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :red_circle: - Default value is not part of the Remediation. Also this is not the standard in the rest of policies
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Chrone should not be running if any other time synchronization method is used. This should be taking into account in the check. This is also specified in the remediation


Expected Pass - :red_circle:
```
{"type":"check","id":1356623917,"policy":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.","policy_id":"cis_ubuntu22-04","check":{"id":28545,"title":"Ensure chrony is running as user _chrony.","description":"The chrony package is installed with a dedicated user account _chrony. This account is granted the access required by the chronyd service.","rationale":"The chronyd service should run with only the required privileges.","remediation":"Add or edit the user line to /etc/chrony/chrony.conf or a file ending in .conf in /etc/chrony/conf.d/: user _chrony OR If another time synchronization service is in use on the system, run the following command to remove chrony from the system: # apt purge chrony Default Value: user _chrony.","compliance":{"cis":"2.1.2.2","cis_csc_v7":"6.1","cis_csc_v8":"8.4","cmmc_v2.0":"AU.L2-3.3.7","pci_dss_v3.2.1":"10.4","pci_dss_v4.0":"10.6,10.6.1,10.6.2,10.6.3","nist_sp_800-53":"AU-7","soc_2":"CC4.1,CC5.2"},"rules":["c:ps -ef -> r:_chrony\\.+chronyd"],"condition":"any","command":"ps -ef","result":"failed"}}

```

</details>


<details>

<summary> 2.1.2.3 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Same as check 2.1.2.2. If any other time syncronization method is running this check should be marked as Not applicable or passed

Expected Passed - :green_circle:
```
{"type":"check","id":1356623917,"policy":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.","policy_id":"cis_ubuntu22-04","check":{"id":28546,"title":"Ensure chrony is enabled and running.","description":"chrony is a daemon for synchronizing the system clock across the network.","rationale":"chrony needs to be enabled and running in order to synchronize the system to a timeserver. Time synchronization is important to support time sensitive security mechanisms and to ensure log files have consistent time records across the enterprise to aid in forensic investigations.","remediation":"IF chrony is in use on the system, run the following commands: Run the following command to unmask chrony.service: # systemctl unmask chrony.service Run the following command to enable and start chrony.service: # systemctl --now enable chrony.service OR If another time synchronization service is in use on the system, run the following command to remove chrony: # apt purge chrony.","compliance":{"cis":"2.1.2.3","cis_csc_v7":"6.1","cis_csc_v8":"8.4","cmmc_v2.0":"AU.L2-3.3.7","pci_dss_v3.2.1":"10.4","pci_dss_v4.0":"10.6,10.6.1,10.6.2,10.6.3","nist_sp_800-53":"AU-7","soc_2":"CC4.1,CC5.2"},"rules":["c:ps -ef -> r:chronyd","c:systemctl is-enabled chrony.service -> r:enabled","c:systemctl is-active chrony.service -> r:active"],"condition":"all","command":"ps -ef","result":"failed"}}

```



</details>


<details>

<summary>2.1.4.1 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :red_circle: - Wrong description, `a kiss-o''-death (KoD)` instead of `a kiss-o'-death (KoD)`
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Same as previous checks, ntp could not be installed in the system and in fact, this check could be incompatible with chrony checks.

Output:
```
root@ip-172-31-7-190:/home/qa# grep -P -- '^\h*restrict\h+((-4\h+)?|-6\h+)default\h+(?:[^#\n\r]+\h+)*(?!(?:\2|\3|\4|\5))(\h*\bkod\b\h*|\h*\bnomodify\b\h*|\h*\bnotrap\b\h*|\h*\bnopeer\b\h*|\h*\bnoquery\b\h*)\h+(?:[^#\n\r]+\h+)*(?!(?:\1|\3|\4|\5))(\h*\bkod\b\h*|\h*\bnomodify\b\h*|\h*\bnotrap\b\h*|\h*\bnopeer\b\h*|\h*\bnoquery\b\h*)\h+(?:[^#\n\r]+\h+)*(?!(?:\1|\2|\4|\5))(\h*\bkod\b\h*|\h*\bnomodify\b\h*|\h*\bnotrap\b\h*|\h*\bnopeer\b\h*|\h*\bnoquery\b\h*)\h+(?:[^#\n\r]+\h+)*(?!(?:\1|\2|\3|\5))(\h*\bkod\b\h*|\h*\bnomodify\b\h*|\h*\bnotrap\b\h*|\h*\bnopeer\b\h*|\h*\bnoquery\b\h*)\h+(?:[^#\n\r]+\h+)*(?!(?:\1|\2|\3|\4))(\h*\bkod\b\h*|\h*\bnomodify\b\h*|\h*\bnotrap\b\h*|\h*\bnopeer\b\h*|\h*\bnoquery\b\h*)\h*(?:\h+\H+\h*)*(?:\h+#.*)?$' /etc/ntp.conf
restrict -4 default kod notrap nomodify nopeer noquery limited
restrict -6 default kod notrap nomodify nopeer noquery limited
```

Expected Failed - :green_circle:
```
- "f:/etc/ntp.conf -> r:restrict -4 default|restrict default && r:kod && r:notrap && r:nomodify && r:nopeer && r:noquery"
- "f:/etc/ntp.conf -> r:restrict -6 default && r:kod && r:notrap && r:nomodify && r:nopeer && r:noquery"
```


Also checks are wrong. Expected
```
- "f:/etc/ntp.conf -> r:restrict -4 default|restrict && r:kod && r:notrap && r:nomodify && r:nopeer && r:noquery"
- "f:/etc/ntp.conf -> r:restrict -6 default && r:kod && r:notrap && r:nomodify && r:nopeer && r:noquery"
```

</details>


<details>

<summary> 2.1.4.3 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :red_circle: - Typo `privlidge` instead of `priviledge`
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Only one time synchronization method should be in use on the system, but this is not check in this is not ensure. Check could be set as Not applicable if ntp is not running.

Output:
```
root@ip-172-31-7-190:/home/qa# ps -ef | awk '(/[n]tpd/ && $1!="ntp") { print $1 }'
root@ip-172-31-7-190:/home/qa# grep -P -- '^\h*RUNASUSER=' /etc/init.d/ntp
RUNASUSER=ntp
```

Also, it seems that rules are not correct. According to the CIS audit, the system is secure but check is marked as failed

Expected Pass - :red_circle:
```
{"timestamp":"2022-11-02T11:59:50.051+0000","rule":{"level":7,"description":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.: Ensure ntp is running as user ntp.","id":"19007","firedtimes":39,"mail":false,"groups":["sca"],"gdpr":["IV_35.7.d"],"pci_dss":["2.2"],"nist_800_53":["CM.1"],"tsc":["CC7.1","CC7.2"],"cis":["2.1.4.3"],"cis_csc_v7":["6.1"],"cis_csc_v8":["8.4"],"nist_sp_800-53":["AU-7"],"soc_2":["CC4.1","CC5.2"]},"agent":{"id":"000","name":"ip-172-31-7-190"},"manager":{"name":"ip-172-31-7-190"},"id":"1667390390.891870","decoder":{"name":"sca"},"data":{"sca":{"type":"check","scan_id":"1356623917","policy":"SCA policy for Ubuntu Linux 22.04 LTS based on CIS benchmark for Ubuntu Linux 22.04 LTS.","check":{"id":"28548","title":"Ensure ntp is running as user ntp.","description":"The ntp package is installed with a dedicated user account ntp. This account is granted the access required by the ntpd daemon Note: If chrony or systemd-timesyncd are used, ntp should be removed and this section skipped This recommendation only applies if ntp is in use on the system Only one time synchronization method should be in use on the system.","rationale":"The ntpd daemon should run with only the required privlidge.","remediation":"Add or edit the following line in /etc/init.d/ntp: RUNASUSER=ntp Run the following command to restart ntp.servocee: # systemctl restart ntp.service OR If another time synchronization service is in use on the system, run the following command to remove ntp from the system: # apt purge ntp Default Value: user ntp.","compliance":{"cis":"2.1.4.3","cis_csc_v7":"6.1","cis_csc_v8":"8.4","cmmc_v2":{"0":"AU.L2-3.3.7"},"pci_dss_v3":{"2":{"1":"10.4"}},"pci_dss_v4":{"0":"10.6,10.6.1,10.6.2,10.6.3"},"nist_sp_800-53":"AU-7","soc_2":"CC4.1,CC5.2"},"references":"http://www.ntp.org/","command":["ps -ef"],"result":"failed"}}},"location":"sca"}

```

</details>


<details>

<summary> 2.1.4.4 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Only one time synchronization method should be in use on the system, but this is not check in this is not ensure. Check could be set as Not applicable if ntp is not installed.

Expected Passed - :green_circle:

</details>


<details>

<summary> 2.2.1 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :red_circle:

Rule should not be negated:

Current
```
- 'not c:dpkg-query -W -f="${binary:Package}\t${Status}\t${db:Status-Status}\n" xserver-xorg* -> r:no packages found matching|deinstall|not-installed'
```

Expected
```
- 'c:dpkg-query -W -f="${binary:Package}\t${Status}\t${db:Status-Status}\n" xserver-xorg* -> r:no packages found matching|deinstall|not-installed'
```

Also, it is recommended to include
```
- "c:dpkg-query -s xserver-xorg -> r:package 'xserver-xorg' is not installed"
```


Expected Passed - :red_circle:

</details>



<details>

<summary> 2.2.2 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Output:
```
dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' avahi-daemon
avahi-daemon\tinstall ok installed\tinstalled\n
```

Expected - :green_circle:

</details>




<details>

<summary> 2.2.3 :green_circle:  </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Output:
```
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -s cups
Package: cups
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 1079
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 2.4.1op1-1ubuntu4.1
Depends: cups-client (>= 2.4.1op1-1ubuntu4.1), cups-common (>= 2.4.1op1-1ubuntu4.1), cups-core-drivers (>= 2.4.1op1-1ubuntu4.1), cups-daemon (>= 2.4.1op1-1ubuntu4.1), cups-filters, cups-ppdc, cups-server-common (>= 2.4.1op1-1ubuntu4.1), debconf (>= 0.5) | debconf-2.0, ghostscript, libcups2 (= 2.4.1op1-1ubuntu4.1), poppler-utils, procps, libavahi-client3 (>= 0.6.16), libavahi-common3 (>= 0.6.16), libc6 (>= 2.34), libgcc-s1 (>= 3.3.1), libstdc++6 (>= 5), libusb-1.0-0 (>= 2:1.0.16)
Recommends: avahi-daemon, colord
Suggests: cups-bsd, cups-pdf, foomatic-db-compressed-ppds | foomatic-db, smbclient, udev
Conffiles:
 /etc/cups/snmp.conf 47b8f1c3fecdc44e3d1fdee4b9eeb3f5
Description: Common UNIX Printing System(tm) - PPD/driver support, web interface
 The Common UNIX Printing System (or CUPS(tm)) is a printing system and
 general replacement for lpd and the like.  It supports the Internet
 Printing Protocol (IPP), and has its own filtering driver model for
 handling various document types.
 .
 This package provides the parts of CUPS which are needed for using printer
 drivers.
Homepage: https://github.com/OpenPrinting/cups/
Original-Maintainer: Debian Printing Team <debian-printing@lists.debian.org>
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' cups
cups\tinstall ok installed\tinstalled\nrebits@pop-os:~/Wazuh/wazuh$ 
```

Expected - :green_circle:


</details>




<details>

<summary> 2.2.4 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Output:
```
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -s isc-dhcp-server
dpkg-query: package 'isc-dhcp-server' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' isc-dhcp-server
dpkg-query: no packages found matching isc-dhcp-server
```

Expected Passed - :green_circle:

</details>



<details>

<summary> 2.2.5 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Output:
```
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -s slapd
dpkg-query: package 'slapd' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' slapd
slapd\tunknown ok not-installed\tnot-installed\n
```

Expected Passed - :green_circle:

</details>


<details>

<summary> 2.2.6 :red_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :red_circle:

Mitre techniques, tactics and mitigations defined but according to CIS there not exists those fields.

Output:
```
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -s nfs-kernel-server
Package: nfs-kernel-server
Status: install ok installed
Priority: optional
Section: net
Installed-Size: 514
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Source: nfs-utils
Version: 1:2.6.1-1ubuntu1
Replaces: knfs, nfs-server
Provides: knfs, nfs-server
Depends: libblkid1 (>= 2.16), libc6 (>= 2.34), libcap2 (>= 1:2.10), libevent-core-2.1-7 (>= 2.1.8-stable), libsqlite3-0 (>= 3.6.0), libtirpc3 (>= 1.0.2), libuuid1 (>= 2.31.1), libwrap0 (>= 7.6-4~), nfs-common (= 1:2.6.1-1ubuntu1), ucf, netbase, lsb-base, keyutils
Recommends: python3, python3-yaml
Conflicts: knfs, nfs-server
Conffiles:
 /etc/init.d/nfs-kernel-server 18f6ff3495106897ac4dfdc0af1b369a
Description: support for NFS kernel server
 The NFS kernel server is currently the recommended NFS server for use
 with Linux, featuring features such as NFSv3 and NFSv4, Kerberos
 support via GSS, and much more. It is also significantly faster and
 usually more reliable than the user-space NFS servers (from the
 unfs3 and nfs-user-server packages). However, it is more difficult to
 debug than the user-space servers, and has a slightly different
 feature set.
 .
 This package contains the user-space support needed to use the
 NFS kernel server. Most administrators wishing to set up an NFS server
 would want to install this package.
Homepage: https://linux-nfs.org/
Original-Maintainer: Debian kernel team <debian-kernel@lists.debian.org>
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' nfs-kernel-server
nfs-kernel-server\tinstall ok installed\tinstalled\n
```

Expected Failed - :green_circle:

</details>


<details>

<summary> 2.2.7 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Output:
```
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -s bind9 
dpkg-query: package 'bind9' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' bind9
dpkg-query: no packages found matching bind9
```

Expected Passed - :green_circle:

</details>


<details>

<summary> 2.2.8 :green_circle: </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


Output:
```
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -s vsftpd
dpkg-query: package 'vsftpd' is not installed and no information is available
Use dpkg --info (= dpkg-deb --info) to examine archive files.
rebits@pop-os:~/Wazuh/wazuh$ dpkg-query -W -f='${binary:Package}\\t${Status}\\t${db:Status-Status}\\n' vsftpd 
dpkg-query: no packages found matching vsftpd
```

Expected Passed - :green_circle:

</details>

**Comment by Rebits** [comment] 2022-11-02 18:37
### Update - 02/11/2022
- [Check 2.1.2.2](https://github.com/wazuh/wazuh-qa/issues/3445#issuecomment-1301060769)

**Comment by Rebits** [comment] 2022-11-03 16:50
### Update - 03/11/2022
- [Check 2.2.5 - 2.2.16](https://github.com/wazuh/wazuh-qa/issues/3445#issuecomment-1301060769)

**Comment by fabamatic** [comment] 2022-11-04 16:45
Fixed most of the errors with some caveats:

- For many of the checks in the section Time Synchronization configuration is not possible to mark as passed depending on the installed services
- Implemented check 2.1.3.2
- In 2.1.4.1 double `'`  in `a kiss-o''-death` is an scape character (similar to \")
- In 2.1.4.3 was not able to reproduce check failure

**Comment by Rebits** [comment] 2022-11-07 17:38
## Testing after requested changes :large_blue_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15051/commits/cdd8c21e3c0ad4d3c0dcb1b7a275661db34b8108

***

### Results

**Comment by Rebits** [comment] 2022-11-07 18:05
### Update
- [Check 2.1.2.2-2.1.4.4](https://github.com/wazuh/wazuh-qa/issues/3445#issuecomment-1305960807)

**Comment by Rebits** [comment] 2022-11-08 09:46
### Update 
- [Finish second manual testing interaction](https://github.com/wazuh/wazuh-qa/issues/3445#issuecomment-1305960807)

**Comment by fabamatic** [comment] 2022-11-08 20:13
Fixed errors in  2.1.3.2 and 2.2.13

**Comment by Rebits** [comment] 2022-11-09 09:33
## Testing after requested changes :red_circle: 

- **Tester**: @Rebits
- **PR commit**:  https://github.com/wazuh/wazuh/pull/15051/commits/cdd8c21e3c0ad4d3c0dcb1b7a275661db34b8108

***

### Results

<details>

<summary> 2.1.3.2 :green_circle:</summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:


</details>

<details>

<summary> 2.2.13 </summary>

- **Title**: :green_circle:
- **Description**: :green_circle:
- **Rationale**: :green_circle:
- **Remediation**: :green_circle:
- **Impact**: :black_circle:
- **Compliance**: :green_circle:
- **References**: :green_circle:
- **Rules**: :green_circle:

</details>

**Comment by jmv74211** [comment] 2022-11-09 09:55
## Closing conclusion 👍🏼

|| |
|-|-|
| 🟢 | Solved |

All bugs encountered and reported have been solved in this development:

**(1) Error in rules and checks** 🟢

- 2.1.2.2: Bad remediation and rules.
- 2.1.2.3: Bad rules
- 2.1.4.1: Bad description and rules.
- 2.1.4.3: Bad rules
- 2.1.4.4: Bad rules. 
- 2.2.1: Bad rules.
- 2.2.3: Bad rules.
- 2.2.4: Bad rules.
- 2.2.5: Bad rules.
- 2.2.6: Bad compliance and rules.
- 2.2.7: Bad rules.
- 2.2.8: Bad rules.
- 2.2.9:  Bad rules.
- 2.2.10: Bad rules.
- 2.2.11: Bad rules.
- 2.2.12: Bad rules.
- 2.2.13: Bad rules. 
- 2.2.14: Bad rules.
- 2.2.16: Bad rules.

**Closed** 2022-11-09 11:06 UTC
Labels: team/qa, target/4.4.0, type/dev-testing, subteam/qa-main
