### ISSUE TITLE
Agent_simulator response to centralized configuration file

### ISSUE THREAD

**Issue by Selutario** [wazuh/wazuh-qa#1284] opened 2021-05-04 08:36 UTC
## Description

Hey team!

We are finding many errors like the one below in the `ossec.conf` of the cluster pipeline tests. 
```
2021/05/03 12:20:50 wazuh-remoted: WARNING: (1246): Unable to send file 'merged.mg' to agent ID '483'.
```

Agent_simulator tool is used in this case. It seems that the simulator should fake a response when the managers try to send the `merged.mg` file to each agent, so this error is not spammed in the logs.

Regards,
Selu.

**Comment by BraulioV** [comment] 2021-05-04 10:09
Hi @Selutario,

That's not a bug in the agent simulator tool. When that message appears in the manager it actually means that it couldn't send the `merged.mg` file to the agent because it is disconnected.

When the manager sends a `merged.mg` file to a simulated agent, it automatically changes the checksum of its effective configuration and answers back to the manager.

**Closed** 2021-05-04 10:43 UTC
Labels: agent_simulator, bug, qa
