### ISSUE TITLE
Let Logcollector try to open missing files perpetually

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3659] opened 2022-12-09 12:56 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.5.0|https://github.com/wazuh/wazuh/issues/13256|https://github.com/wazuh/wazuh/pull/15647|

## Description

This PR aims to modify the default value of Logcollector's internal option open_attempts, so that the program does not stop trying to open missing log files.

## Proposed checks

- [ ] Start Logcollector with a missing log file, and then create it.
- [ ] Start Logcollector with an existing log file, and then delete it.
- [ ] Create the file back and put some lines in it.
- [ ] Delete the file again.

## Expected results

Logcollector should keep trying to open the file, no matter the number of attempts (one each `vcheck_files` seconds).

On the other hand, we expect no repeating logs (having debug mode disabled) while Logcollector keeps failing to open a missing file.

#### ossec.conf

```xml
<localfile>
  <log_format>syslog</log_format>
  <location>/root/test.log</location>
</localfile>
```

#### local_internal_options.conf

I recommend to set up this internal option, in order to test this behavior more quicky:

```shell
logcollector.vcheck_files=2
```

**Comment by Rebits** [comment] 2023-01-11 15:56
## Tester review

| Tester | PR commit               |
|--------|-------------------------|
| @Rebits| https://github.com/wazuh/wazuh/pull/15647/commits/bd31828ab7f8a88bd485fab631c0acadabe2388a  | 

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  Ubuntu |    Ubuntu 20.04     | EC2 |    ami-003530de8839921c4 |


### Tested packages

| `wazuh-manager` | 
|-----------------|
|  [Deb manager](https://packages-dev.wazuh.com/warehouse/test/4.5/deb/var/wazuh-manager_4.5.0-qa.vr.3659_amd64.deb) | 

### Status

- [x] In progress
- [ ] Pending Review
- [ ] QA Manager approved (@jmv74211)
- [ ] Development team leader approved (@vikman90 )

**Comment by Rebits** [comment] 2023-01-11 15:56
## Tester results :large_blue_circle:

<details>

<summary> Start Logcollector with a missing log file, and then create it  :large_blue_circle:</summary>

</details>


<details>

<summary> Start Logcollector with an existing log file, and then delete it  :large_blue_circle: </summary>

</details>


<details>

<summary>Create the file back and put some lines in it  :large_blue_circle: </summary>

</details>


<details>

<summary> Delete the file again  :large_blue_circle: </summary>

</details>


<details>

<summary> 4.4.0->4.5.0 Upgrade  :large_blue_circle: </summary>



</details>

**Comment by jmv74211** [comment] 2023-01-23 16:47
# QA Review

- **Type**: Manual testing.
- **Status**: Requested improvements  🟡 
- **Comments**:  Everything seems to be correct, however, @Rebits suggests the following improvement:
  - **(1) There is no feedback if a file is reloaded and is being monitored again**: for example, if we `monitor a file -> delete it --> create it again`.

**Comment by vikman90** [comment] 2023-01-24 07:53
@Rebits @jmv74211 thanks for the review. Regarding the requested improvement, I could reproduce that:

<details><summary><h4>No file on Logcollector start</h4></summary>

```
2023/01/24 08:46:32 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2023/01/24 08:46:32 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/dpkg.log'.
2023/01/24 08:46:32 wazuh-logcollector: ERROR: (1103): Could not open file '/root/test.log' due to [(2)-(No such file or directory)].
2023/01/24 08:46:32 wazuh-logcollector: INFO: (1950): Analyzing file: '/root/test.log'.
2023/01/24 08:46:32 wazuh-logcollector: INFO: Started (pid: 1713).
>>> touch /root/test.log
```

</details>
<details><summary><h4>Delete file while Logcollector is running</h4></summary>

```
2023/01/24 08:47:33 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/ossec/logs/active-responses.log'.
2023/01/24 08:47:33 wazuh-logcollector: INFO: (1950): Analyzing file: '/var/log/dpkg.log'.
2023/01/24 08:47:33 wazuh-logcollector: INFO: (1950): Analyzing file: '/root/test.log'.
2023/01/24 08:47:33 wazuh-logcollector: INFO: Started (pid: 1752).
>>> rm /root/test.log
2023/01/24 08:47:43 wazuh-logcollector: INFO: (1959): File '/root/test.log' no longer exists.
>>> touch /root/test.log
```

</details>

Please open an issue for it. This requirement is beyond the purpose of this task, which is simply to change the default value of an option.

Cheers!

**Comment by jmv74211** [comment] 2023-01-24 11:02
## Closing conclusion 👍🏼  

Everything seems to work properly. A new issue has been created [wazuh#15995](https://github.com/wazuh/wazuh/issues/15995) to improve the logging. That issue is not caused by the tested changes/development, so it will be worked in the future.

**Closed** 2023-01-24 18:00 UTC
Labels: team/qa, feature/logcollector, target/4.5.0, type/dev-testing, subteam/qa-main
