### ISSUE TITLE
API integration test fails due to startup time underestimation for low resources environments

### ISSUE THREAD

**Issue by jnasselle** [wazuh/wazuh-qa#4568] opened 2023-10-02 12:21 UTC
| Target version | Release candidate | Main release testing issue |
|--------------------|--------------------|--------------------|
| v4.5.3 |               RC 2     | https://github.com/wazuh/wazuh/issues/19325|

## Description

During https://github.com/wazuh/wazuh/issues/19325, it was found that API integration test are failing, showing the following error
```
2023-09-29 00:00:29,026 - wazuh_testing - ERROR - Could not find this event in /var/ossec/logs/api.log: .*Listening on 0.0.0.0:55000.+

```

[manager_html_report_Test_integration_B43367_20230929003522.zip](https://github.com/wazuh/wazuh-qa/files/12782518/manager_html_report_Test_integration_B43367_20230929003522.zip)
https://ci.wazuh.info/job/Test_integration/43367

### Details

- Issue labeled as known issue after discussing it with @Selutario , because this error was seen in previous scenarios but without a propper issue
- Replay of Jenkins job shows a successful result

**Comment by GGP1** [comment] 2023-11-09 18:42
## Update

Executed the `test_api` twice to reproduce the error but it passed on all its executions.

Launcher build: https://ci.wazuh.info/job/Test_integration_launcher/226
API build: https://ci.wazuh.info/job/Test_integration/44568
Artifacts: [archive.zip](https://github.com/wazuh/wazuh-qa/files/13311616/archive.zip)

Launcher build 2: https://ci.wazuh.info/job/Test_integration_launcher/227
API build 2: https://ci.wazuh.info/job/Test_integration/44569

### Instances comparison

The `test_integration` run on `m4.large` instances whereas the `test_integration_endpoints` in `t3a.medium`.

Instance | vCPU | Mem (GiB) | Storage | Network Performance
-- | -- | -- | -- | --
m4.large | 2 | 8 | EBS-only | Moderate
t3a.medium | 2 | 4 | EBS-Only | Up to 5

The `test_integration` pipeline uses instances with higher resources, so that shouldn't be a problem.

### Past executions

In the last executions, there were no reports of this issue.

- [4.6.0 - Beta 1](https://github.com/wazuh/wazuh/issues/19198#issue-1911129892)
- [4.6.0 - RC 1](https://github.com/wazuh/wazuh/issues/19529#issue-1933160600)
- [4.7.0 - Alpha 1](https://github.com/wazuh/wazuh/issues/19669#issue-1945424572)
- [4.7.0 - Alpha 2](https://github.com/wazuh/wazuh/issues/20038#issue-1976222037)
- [4.7.1 (development)](https://ci.wazuh.info/job/Test_integration/44541/): [archive.zip](https://github.com/wazuh/wazuh-qa/files/13311568/archive.zip)
- [4.7.0 (nightly)](https://ci.wazuh.info/job/Test_integration/44518/): [archive.zip](https://github.com/wazuh/wazuh-qa/files/13311585/archive.zip)
- [4.9.0 (development)](https://ci.wazuh.info/job/Test_integration/44517/): [archive.zip](https://github.com/wazuh/wazuh-qa/files/13311613/archive.zip)

## Conclusion

The error couldn't be reproduced and seems to have occurred due to the changes in the `4.5.3` version that were later fixed or due to an extraordinary issue in the instance used to run it. 

I think this issue should be closed and re-opened if the same error is encountered in the future.

**Comment by EduLeon12** [comment] 2023-11-09 19:54
## Review Update

I can confirm that, after looking at the provided logs in the different testing stages for the API, the error couldn't be reproduced and the cause of it is uncertain, I approve the decision to close the issue and for it to be re-opened if necessary.

**Closed** 2023-11-10 10:18 UTC
Labels: feature/api, level/task, type/bug, qa_known
