### ISSUE TITLE
Integration test to verify that there are no exceptions in the upgrade process queries

### ISSUE THREAD

**Issue by Nicogp** [wazuh/wazuh-qa#2954] opened 2022-06-02 13:56 UTC
|Related issue|Related PR|
|---|---|
|https://github.com/wazuh/wazuh/issues/13503|https://github.com/wazuh/wazuh/pull/13662|

### Description
The goal of this issue is to create an integration test for agent upgrade and task modules that covers the case described at https://github.com/wazuh/wazuh/issues/13503

The error occurred when the script launched agents to update and then began to check the status of the tasks and in one of them if the `update_time `field does not match format `'%Y/%m/%d %H:%M:%S'` the script fails.

The script fails because, when wazuh API queries for upgrade_status, it expects the update_time field to have the format `'%Y/%m/%d %H:%M:%S'` or be null, but when the field was null, the task module added it with the value `"0"`

The implemented solution was to remove the `update_time `field from the response when the value is `0` or `null`.

**Comment by jmv74211** [comment] 2022-06-17 09:16
This type of testing does not correspond to integration tests, but would be typical of a system test.

In this case we are working on the development of a framework that allows us to perform this type of testing, so this issue is blocked until the development is completed.

**Comment by davidjiglesias** [comment] 2023-06-14 09:15
From my point of view, this issue involves testing the interaction between the agent upgrade and task modules in a specific scenario. The error is tied to the interaction between the upgrade_status query from the Wazuh API, and the response from the task module. In this case, the main concern is the format of the update_time field and how it's handled between these two modules. Therefore, an integration test would be the appropriate testing method to verify the solution works as intended when these two modules interact.

**Comment by vikman90** [comment] 2024-04-10 17:15
Closing this issue. Superseded by version 5.0.

**Closed** 2024-04-10 17:18 UTC
Labels: test/integration, test-development, level/task, type/enhancement
