### ISSUE TITLE
Libstdc++ does not install with the NSI executable 

### ISSUE THREAD

**Issue by BelenValdivia** [wazuh/wazuh-qa#3542] opened 2022-11-01 15:28 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|       4.4.0                 |      https://github.com/wazuh/wazuh/issues/15268                  |     https://github.com/wazuh/wazuh/pull/15271               |

## Description

This issue aims to correct the lack of installation of this library causing the service not to start when the installer is the .exe generated after the cross-compilation of windows.

### Reproduce the bug

  1.  Install wazuh agent 4.4 using .exe
  2. Check the error in logs ossec.log:       

      ![Image](https://user-images.githubusercontent.com/26927338/199320937-75c0625f-1e56-4b58-90f5-b92561e53f1d.png)
   
### Upgrade from 4.4 to Core branch with fix using .exe

   1.  Upgrade wazuh agent
   2.  Check that binaries are loading libraries with  https://hshrzd.wordpress.com/pe-bear/
          -  libstdc++-6.dll
          -  libgcc_s_dw2-1.dll
   3. Check syscollector works correctly
   4. No errors in ossec log
        
### Fresh install Windows- Core branch fix using .exe
  
  1.  Install  wazuh-agent
  2. Check that binaries are loading the libraries with https://hshrzd.wordpress.com/pe-bear/ 
        -  libstdc++-6.dll
        -  libgcc_s_dw2-1.dll
  3. Check syscollector works correctly
  4. No errors in ossec log
...

## Expected results

The service starts when the installer is the .exe. The installer generated in this branch distributes the library correctly.

**Comment by BelenValdivia** [comment] 2022-11-02 14:30
# Tester review

| Tester | PR commit               | 
|--------|-------------------------|
| @BelenValdivia   | https://github.com/wazuh/wazuh/pull/15271/commits/cef49a0d9d7b97d42498e455935d826184b5cc28 | 



### Testing environment

| OS                  | OS version | Deployment | Image/AMI               |
| ------------------- | ---------- | ---------- | ----------------------- |
| CentOS             | CentOS 8        | vagrant       | `qactl/centos_8` |
| Windows |  Windows Server 2019 | vagrant | 'qactl/windows_2019' |



### Tested executable file

| OS     | Package                                                                             |
| ------ | ----------------------------------------------------------------------------------- |
| Windows      |     .exe generated from sources                                                                         |



## Status

- [x] In progress
- [ ] Pending Review
- [ ] QA team leader approved @damarisg 
- [ ] QA manager approved @jmv74211 
- [ ] Development team leader approved 


## Conclusion

**Comment by BelenValdivia** [comment] 2022-11-02 14:45
## Reproduce the bug

<details><summary> Check the error in ossec.log </summary>
 Error reproduced with the executable file 4.4.0 version:

 ![syscollector error](https://user-images.githubusercontent.com/26927338/199520250-442e6932-da1d-4fe7-bfbd-118520b8dc78.png)



</details>

**Comment by BelenValdivia** [comment] 2022-11-03 19:41
11/3/2022
- Found windows upgrade bug
- Tested upgrade:
   - Checked libraries are loaded
   - Checked that there aren't errors in ossec log
   - Checked that syscollector works correctly.

**Comment by BelenValdivia** [comment] 2022-11-04 18:32
11/4/2022
- Tested fresh install
     - Checked libraries are loaded
     - Checked that there aren't errors in ossec log
     - Checked that syscollector works correctly.

**Comment by damarisg** [comment] 2022-11-07 13:26
## QA review

- **Type**: Manual Testing
- **Status**: Approved 🟢
- **Comment**: Everything seems to be working properly.

**Comment by jmv74211** [comment] 2022-11-08 08:50
## Closing conclusion 👍🏼  

|| |
|-|-|
| 🔵 | Proposed to be fixed in future versions or developments | 


The development has been approved taking into account the following considerations:

**(1) Windows upgrade with .exe installer shows pop-ups with errors.** 🔵 

After discussing with the development team, this is a behavior which is not caused by this development. The following issue [wazuh#15295](https://github.com/wazuh/wazuh/issues/15295) has been opened for reporting and will be investigated and fixed in future releases..

---

Otherwise, no bugs have been found and the changes seem to solve the problem raised in the issue.

**Closed by jmv74211** 2022-11-08 08:50 UTC
Labels: team/qa, type/manual-testing, target/4.4.0, type/dev-testing, role/qa-data-pirates, subteam/qa-rainbow
