### ISSUE TITLE
System basic_environment tests fail in 4.8.0-beta4

### ISSUE THREAD

**Issue by Rebits** [wazuh/wazuh-qa#5102] opened 2024-03-14 11:21 UTC
### Description

During [Release 4.8.0 - Beta 4 - System tests](https://github.com/wazuh/wazuh/issues/22481) it has been detected unexpected errors
in the Basic Environment environment tests `test_agent_auth` and  `test_enrollment`

- `test_agent_auth`: 

The expected log was not found during the test
```
E                   TimeoutError: Did not found the expected callback in wazuh-agent1: .*Requesting a key from server: 172\.24\.27\.2
```

However we can see that it is present in the agent log file:

```
2024/03/13 18:20:48 agent-auth: INFO: Requesting a key from server: 172.24.27.2
```

Further research is required

- `test_enrollment`

Expected log was not found during the test

```
E                   TimeoutError: Did not found the expected callback in wazuh-agent1: .*Requesting a key from server: 172.24.27.2
```

However we can see that it is present in the agent log file:
```
2024/03/13 19:03:33 wazuh-agentd[44457] enrollment_op.c:129 at w_enrollment_request_key(): INFO: Requesting a key from server: 172.24.27.2
```

Further research is required

- **Test case**: 
  - test_agent_auth[manager_ipv4_agent_ipv4-ipv4-yes]
  - test_agent_auth[manager_ipv4_agent_ipv4-dns-no]
  - test_agent_auth[manager_ipv6_agent_ipv6-dns-yes]
  - test_agent_auth[manager_both_agent_ipv4-dns-no]
  - test_agent_auth[manager_ipv4_agent_both-ipv4-yes]
  - test_agent_enrollment[manager_both_agent_both-ipv4-no]
  - test_agent_enrollment[manager_both_agent_both-ipv6-yes]
  - test_agent_enrollment[manager_both_agent_both-dns-yes]
  - test_agent_enrollment[manager_ipv4_agent_ipv4-ipv4-no]
  
- **Report**:  [basic_env.zip](https://github.com/wazuh/wazuh-qa/files/14601431/basic_env.zip)

**Comment by juliamagan** [comment] 2024-03-15 13:58
As in other iterations, the log does appear. The problem is in the HostMonitor, which does not work as expected in virtualized environments. We can do an analysis and refactor of this method, or wait for the migration of the system tests.

In the meantime, it is proposed to mark the issue as qa_known, and when the system tests fail it, before opening an issue directly, check the environment logs.

**Comment by juliamagan** [comment] 2024-04-10 10:40
After the meeting with @davidjiglesias and @rauldpm, we are going to close this issue as not planned, and the system tests will be launched locally if necessary until we can migrate these tests to the new framework.

**Closed by juliamagan** 2024-04-10 10:40 UTC
Labels: level/task, type/bug, qa_known
