### ISSUE TITLE
Fix memory leaks in wazuh-analysisd when parsing and matching rules

### ISSUE THREAD

**Issue by vikman90** [wazuh/wazuh-qa#3993] opened 2023-03-03 12:44 UTC
| Target version | Related issue | Related PR |
|--------------------|--------------------|-----------------|
|4.4.0|https://github.com/wazuh/wazuh/issues/16304|https://github.com/wazuh/wazuh/pull/16321|

## Description

This PR aims to fix 27 memory leaks detected in _wazuh-analysisd_. They're detailed in the related issue.

## Proposed checks

**All these tests must be launched with _wazuh-analysisd_ running on Valgrind**, in order to see the memory leaks.

- [x] Search for memory leaks related with `<if_matched_sid>`:

```sh
for i in {1..3}; do echo 'device="SFW" date=2000-12-01 time=17:19:06 timezone="+01" device_name="XXXX" device_id=1234567 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Denied" status="Deny"'; done | wazuh-logtest
```

- [x] Search for memory leaks related with `<if_matched_group>`:

```sh
for i in {1..3}; do echo 'device="SFW" date=2000-12-01 time=17:19:06 timezone="+01" device_name="XXXX" device_id=12345678 log_id=010101010101 log_type="Firewall" log_component="Firewall Rule" log_subtype="Denied" status="Deny"'; done | wazuh-logtest
```
(Note that `device_id` is different).

- [x] Produce any ruleset parsing warning more than 50 times (for instance, a duplicate rule). and run one of the commands above.

## Expected results

- No memory leaks should appear.
- However, the behavior hasn't changed.

## Configuration and considerations

<details><summary><h3>Ruleset</h3></summary>

```xml
<rule id="999280" level="3">
  <if_sid>70021</if_sid>
  <field name="device_id">^1234567$</field>
  <description>Traffic Denied</description>
  <options>no_full_log</options>
</rule>

<rule id="999281" level="5" timeframe="3600">
  <if_matched_sid>999280</if_matched_sid>
  <description>Traffic Denied (SID level-1)</description>
</rule>

<rule id="999282" level="7" timeframe="3600">
  <if_matched_sid>999281</if_matched_sid>
  <description>Traffic Denied (SID level-2)</description>
</rule>

<rule id="999283" level="3">
  <if_sid>70021</if_sid>
  <field name="device_id">^12345678$</field>
  <description>Traffic Denied</description>
  <options>no_full_log</options>
  <group>test_if_group_1,</group>
</rule>

<rule id="999284" level="5" timeframe="3600">
  <if_matched_group>test_if_group_1</if_matched_group>
  <description>Traffic Denied (group level-1)</description>
  <group>test_if_group_2,</group>
</rule>

<rule id="999285" level="7" timeframe="3600">
  <if_matched_group>test_if_group_2</if_matched_group>
  <description>Traffic Denied (group level-2)</description>
</rule>
```

</details>

***

### Status

- [x] In progress (@juliamagan)
- [x] Pending Review
- [x] QA manager approved (@jmv74211)
- [x] Development team leader approved (@vikman90)

**Comment by juliamagan** [comment] 2023-03-06 11:56
## Review data

| Tester | PR commit               |
|--------|-------------------------|
| @juliamagan  |  https://github.com/wazuh/wazuh/pull/16321/commits/daddba13515691d1ed7096c8bb45429174f3bbfd  |

### Testing environment

| OS | OS version | Deployment                                    | Image/AMI | Notes |
|----|------------|-----------------------------------------------|-----------|-------|
|  CentOS  | 8 | Vagrant | qactl/centos_8 |


### Tested packages

Manager was built from sources since Jenkins is down

**Comment by juliamagan** [comment] 2023-03-06 12:07
## Testing results

### Reproduce the bug

<details>
<summary><b>Case 1:</b> Search for memory leaks related with <code>&lt;if_matched_sid&gt;</code></summary>
<br>


</details>


<details>
<summary><b>Case 2:</b> Search for memory leaks related with <code>&lt;if_matched_group&gt;</code></summary>
<br>


</details>

<details>
<summary><b>Case 3:</b> Produce any ruleset parsing warning more than 50 times (for instance, a duplicate rule). and run one of the commands above.</summary>
<br>


</details>

### Fresh install

<details>
<summary><b>Case 1:</b> Search for memory leaks related with <code>&lt;if_matched_sid&gt;</code></summary>
<br>


</details>


<details>
<summary><b>Case 2:</b> Search for memory leaks related with <code>&lt;if_matched_group&gt;</code></summary>
<br>


</details>

<details>
<summary><b>Case 3:</b> Produce any ruleset parsing warning more than 50 times (for instance, a duplicate rule). and run one of the commands above.</summary>
<br>


</details>

### Upgrade

<details>
<summary><b>Case 1:</b> Search for memory leaks related with <code>&lt;if_matched_sid&gt;</code></summary>
<br>


</details>


<details>
<summary><b>Case 2:</b> Search for memory leaks related with <code>&lt;if_matched_group&gt;</code></summary>
<br>


</details>

<details>
<summary><b>Case 3:</b> Produce any ruleset parsing warning more than 50 times (for instance, a duplicate rule). and run one of the commands above.</summary>
<br>


</details>

**Comment by juliamagan** [comment] 2023-03-07 09:20
## Conclusion 🟢 

Everything seems to work as expected

**Comment by jmv74211** [comment] 2023-03-07 10:08
@juliamagan we need to check the functional behavior, ie, check that `<if_matched_sid>`  and `<if_matched_group>` work as expected. As @vikman90  comments, the behavior hasn't changed.

Please perform some functional tests of these labels to show its correct operation.

**Comment by jmv74211** [comment] 2023-03-07 17:18
## Closing conclusion 👍🏼  

>Note: The requested functional tests have been added to the testing results

Everything seems to be working properly.

**Closed** 2023-03-15 16:01 UTC
Labels: team/qa, dev-testing, subteam/qa-main, level/task, type/test
